/**
 * AIGC（生图 / 生视频）收录清单的**人工定稿源数据**。
 * 一个对象 = 站内一条收录，`_verify/aigc-generate.mjs` 读它生成 `src/content/aigc/<slug>.md`。
 *
 * 字段口径见 docs/项目结构/项目说明.md，这里只记「为什么要这么填」：
 *   slug          文件名 = URL，英文小写连字符
 *   title         官方写法（厂商怎么写就怎么写）
 *   org           发布方；family 是家族（决定左侧「所属」分组）
 *   released      官方首次公开发布（权重可下载）的日期；官方没给明确日期时用 HF 仓库创建日，
 *                 `_verify/docs-list.mjs` 会把与 HF 仓库创建日差值 ≥3 天的条目打出来复核
 *   output        image / video
 *   tags          架构固定枚举：DiT / MMDiT / 自回归 / 离散扩散
 *   commercial    由 license 原文判（Apache-2.0 / MIT → 可商用；自定义协议带门槛 → 有条件可商用；NC → 不可商用）
 *   repo          HF 仓库 ID；`aigc-generate.mjs` 用它去 `_verify/aigc-enrich.json` 取真实参数量与仓库创建日
 *   vram          只在官方卡片写明了显存要求时才填，否则留空
 *
 * 收录线（比 LLM 那条松一点，AIGC 里「站在开源权重上继续训练」是常态）：
 *   收 机构第一方发布、自己训练、以自己的名义放权重的模型（即使初始化自开源权重）；
 *   不收 个人 / 社区的微调、LoRA、merge、ControlNet、量化与蒸馏再发布（Chroma、Kroma、各类 GGUF 都是这一类），
 *   不收 只有 API 的闭源服务（Kling、Seedance、Midjourney、Nano Banana、PixVerse…），
 *   不收 纯修复 / 超分 / 理解型模型（SeedVR2 之类）。
 */

export const PLANS = [
  /* ============================ 生图 · 2025 ============================ */
  {
    slug: 'lumina-image-2-0',
    title: 'Lumina-Image 2.0',
    org: '上海人工智能实验室 Alpha-VLLM',
    family: 'Lumina',
    released: '2025-01-22',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '流匹配扩散 Transformer',
    params: '2.6B',
    repo: 'Alpha-VLLM/Lumina-Image-2.0',
    summary: '上海 AI Lab 的 2.6B 流匹配扩散 Transformer 文生图模型，以小体量在 GenEval 等基准上对标大得多的模型。',
    links: {
      hf: 'https://huggingface.co/Alpha-VLLM/Lumina-Image-2.0',
      github: 'https://github.com/Alpha-VLLM/Lumina-Image-2.0',
      paper: 'https://arxiv.org/abs/2503.21758',
    },
  },
  {
    slug: 'cogview4-6b',
    title: 'CogView4-6B',
    org: '智谱 AI',
    family: 'CogView',
    released: '2025-03-04',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'DiT（GLM-4-9B 作文本编码器）',
    params: '6.4B',
    repo: 'zai-org/CogView4-6B',
    summary: '智谱开源的 6B 文生图模型，用 GLM-4-9B 作文本编码器，是首批能稳定渲染汉字的开源生图模型之一。',
    links: {
      hf: 'https://huggingface.co/zai-org/CogView4-6B',
      github: 'https://github.com/THUDM/CogView4',
    },
  },
  {
    slug: 'sana-1-5-4-8b',
    title: 'SANA 1.5 4.8B',
    org: 'NVIDIA',
    family: 'SANA',
    released: '2025-03-16',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '线性扩散 Transformer（Linear-DiT）',
    params: '4.8B',
    repo: 'Efficient-Large-Model/SANA1.5_4.8B_1024px',
    summary: 'NVIDIA 的线性扩散 Transformer 文生图模型，用深度增长把 4.8B 版本推到当时 GenEval 的高位，是高效生图路线的代表作。',
    links: {
      hf: 'https://huggingface.co/Efficient-Large-Model/SANA1.5_4.8B_1024px',
      github: 'https://github.com/NVlabs/Sana',
      paper: 'https://arxiv.org/abs/2501.18427',
    },
  },
  {
    slug: 'sana-sprint-1-6b',
    title: 'SANA-Sprint 1.6B',
    org: 'NVIDIA',
    family: 'SANA',
    released: '2025-03-21',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '线性 DiT + 连续时间一致性蒸馏',
    params: '1.6B',
    repo: 'Efficient-Large-Model/Sana_Sprint_1.6B_1024px',
    summary: '用连续时间一致性蒸馏把 SANA 压到 1～4 步出图的一步扩散模型，为实时、低成本的本地生图提供了开源方案。',
    links: {
      hf: 'https://huggingface.co/Efficient-Large-Model/Sana_Sprint_1.6B_1024px',
      github: 'https://github.com/NVlabs/Sana',
      paper: 'https://arxiv.org/abs/2503.09641',
    },
  },
  {
    slug: 'hidream-i1',
    title: 'HiDream-I1',
    org: 'HiDream.ai 智象未来',
    family: 'HiDream',
    released: '2025-04-07',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '稀疏 DiT',
    params: '17.1B',
    repo: 'HiDream-ai/HiDream-I1-Full',
    summary: '国产 17B 稀疏 DiT 文生图基座，发布即登顶开源生图多个榜单，MIT 许可下可直接商用。',
    links: {
      hf: 'https://huggingface.co/HiDream-ai/HiDream-I1-Full',
      github: 'https://github.com/HiDream-ai/HiDream-I1',
      paper: 'https://arxiv.org/abs/2505.22705',
    },
  },
  {
    slug: 'step1x-edit',
    title: 'Step1X-Edit',
    org: '阶跃星辰 StepFun',
    family: 'Step1X',
    released: '2025-04-27',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'MLLM + DiT（7B 理解 + 12B 生成）',
    params: '19B',
    repo: 'stepfun-ai/Step1X-Edit',
    summary: '阶跃星辰开源的 19B 图像编辑模型，用自然语言指令改图并保持身份一致，是 2025 上半年最强的开源编辑模型之一。',
    links: {
      hf: 'https://huggingface.co/stepfun-ai/Step1X-Edit',
      github: 'https://github.com/stepfun-ai/Step1X-Edit',
      paper: 'https://arxiv.org/abs/2504.17761',
    },
  },
  {
    slug: 'hidream-e1',
    title: 'HiDream-E1',
    org: 'HiDream.ai 智象未来',
    family: 'HiDream',
    released: '2025-04-28',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '指令式图像编辑 DiT',
    params: '17.1B',
    repo: 'HiDream-ai/HiDream-E1-Full',
    summary: 'HiDream 在 I1 之后开源的指令式图像编辑模型，把自然语言修图做成 MIT 许可下的开源基线。',
    links: {
      hf: 'https://huggingface.co/HiDream-ai/HiDream-E1-Full',
      github: 'https://github.com/HiDream-ai/HiDream-E1',
      paper: 'https://arxiv.org/abs/2505.22705',
    },
  },
  {
    slug: 'f-lite',
    title: 'F Lite',
    org: 'Freepik',
    family: 'F Lite',
    released: '2025-04-29',
    output: 'image',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'CreativeML Open RAIL-M',
    architecture: 'DiT（T5-XXL 编码器）',
    params: '10B',
    repo: 'Freepik/F-Lite',
    summary: 'Freepik 与 fal 联合开源、只用约 8000 万张版权安全数据从零训练的 10B 文生图模型，为「合规数据训练大模型」提供了开源样本。',
    links: {
      hf: 'https://huggingface.co/Freepik/F-Lite',
      github: 'https://github.com/fal-ai/f-lite',
    },
  },
  {
    slug: 'blip3-o-8b',
    title: 'BLIP3-o 8B',
    org: 'Salesforce Research',
    family: 'BLIP3-o',
    released: '2025-05-12',
    output: 'image',
    tags: ['自回归'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '统一多模态 Transformer（自回归 + 流匹配生成）',
    params: '8B',
    repo: 'BLIP3o/BLIP3o-Model-8B',
    summary: 'Salesforce 的「先理解后生成」统一多模态模型，用扩散生成语义特征替代 VAE，在 GenEval 上刷新开源纪录。',
    links: {
      hf: 'https://huggingface.co/BLIP3o/BLIP3o-Model-8B',
      github: 'https://github.com/JiuhaiChen/BLIP3o',
      paper: 'https://arxiv.org/abs/2505.09568',
    },
  },
  {
    slug: 'show-o2',
    title: 'Show-o2',
    org: '新加坡国立大学 ShowLab',
    family: 'Show-o',
    released: '2025-06-05',
    output: 'image',
    tags: ['自回归'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '原生统一多模态 Transformer（自回归 + 流匹配双头）',
    params: '7B',
    repo: 'showlab/show-o2-7B',
    summary: 'NUS ShowLab 的原生统一多模态模型，用自回归语言头加流匹配生成头同时做图像理解与生成。',
    links: {
      hf: 'https://huggingface.co/showlab/show-o2-7B',
      github: 'https://github.com/showlab/Show-o',
      paper: 'https://arxiv.org/abs/2506.15564',
    },
  },
  {
    slug: 'omnigen2',
    title: 'OmniGen2',
    org: '北京智源研究院 VectorSpaceLab',
    family: 'OmniGen',
    released: '2025-06-16',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '解耦式统一多模态 Transformer（Qwen2.5-VL + 扩散分支）',
    params: '4B',
    repo: 'OmniGen2/OmniGen2',
    summary: '把文生图、指令修图与上下文中生成放进一套权重的统一多模态模型，发布时编辑能力位列开源第一梯队。',
    links: {
      hf: 'https://huggingface.co/OmniGen2/OmniGen2',
      github: 'https://github.com/VectorSpaceLab/OmniGen2',
      paper: 'https://arxiv.org/abs/2506.18871',
    },
  },
  {
    slug: 'flux-1-kontext-dev',
    title: 'FLUX.1 Kontext [dev]',
    org: 'Black Forest Labs',
    family: 'FLUX',
    released: '2025-06-26',
    output: 'image',
    tags: ['MMDiT'],
    commercial: '不可商用',
    license: 'FLUX.1 [dev] Non-Commercial License',
    architecture: 'Rectified Flow Transformer (MMDiT)',
    params: '12B',
    repo: 'black-forest-labs/FLUX.1-Kontext-dev',
    summary: 'BFL 的 12B 图像编辑模型，第一次让开放权重具备接近闭源工具的迭代式编辑与角色一致性。',
    links: {
      hf: 'https://huggingface.co/black-forest-labs/FLUX.1-Kontext-dev',
      github: 'https://github.com/black-forest-labs/flux',
      paper: 'https://arxiv.org/abs/2506.15742',
    },
  },
  {
    slug: 'vincie-3b',
    title: 'VINCIE-3B',
    org: '字节跳动 Seed',
    family: 'VINCIE',
    released: '2025-07-02',
    output: 'image',
    tags: ['自回归'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '自回归多模态 Transformer（从视频学上下文编辑）',
    params: '3B',
    repo: 'ByteDance-Seed/VINCIE-3B',
    summary: '字节 Seed 用视频数据训练的多模态图像编辑模型，无需掩码即可完成多轮指令式编辑。',
    links: {
      hf: 'https://huggingface.co/ByteDance-Seed/VINCIE-3B',
      paper: 'https://arxiv.org/abs/2506.10941',
    },
  },
  {
    slug: 'hidream-e1-1',
    title: 'HiDream-E1.1',
    org: 'HiDream.ai 智象未来',
    family: 'HiDream',
    released: '2025-07-16',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '指令式图像编辑 DiT',
    params: '17.1B',
    repo: 'HiDream-ai/HiDream-E1-1',
    summary: 'HiDream 编辑模型的升级版，在 EmuEdit、ReasonEdit 等基准上明显领先前代，并保持 MIT 可商用许可。',
    links: {
      hf: 'https://huggingface.co/HiDream-ai/HiDream-E1-1',
      github: 'https://github.com/HiDream-ai/HiDream-E1',
      paper: 'https://arxiv.org/abs/2505.22705',
    },
  },
  {
    slug: 'skywork-unipic-1-5b',
    title: 'Skywork UniPic 1.5B',
    org: '昆仑万维 Skywork',
    family: 'Skywork UniPic',
    released: '2025-07-29',
    output: 'image',
    tags: ['自回归'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '统一自回归多模态 Transformer（Qwen2.5-1.5B + MAR 解码）',
    params: '1.5B',
    repo: 'Skywork/Skywork-UniPic-1.5B',
    summary: '昆仑万维的 1.5B 统一自回归多模态模型，一套权重同时做图像理解、文生图与图像编辑。',
    links: {
      hf: 'https://huggingface.co/Skywork/Skywork-UniPic-1.5B',
      github: 'https://github.com/SkyworkAI/UniPic',
      paper: 'https://arxiv.org/abs/2508.03320',
    },
  },
  {
    slug: 'flux-1-krea-dev',
    title: 'FLUX.1 Krea [dev]',
    org: 'Black Forest Labs',
    family: 'FLUX',
    released: '2025-07-31',
    output: 'image',
    tags: ['MMDiT'],
    commercial: '不可商用',
    license: 'FLUX.1 [dev] Non-Commercial License',
    architecture: 'Rectified Flow Transformer (MMDiT)',
    params: '12B',
    repo: 'black-forest-labs/FLUX.1-Krea-dev',
    summary: 'BFL 与 Krea 联合开源的 12B 文生图模型，专治过饱和的「AI 感」并追求摄影级真实质感。',
    links: {
      hf: 'https://huggingface.co/black-forest-labs/FLUX.1-Krea-dev',
      github: 'https://github.com/black-forest-labs/flux',
    },
  },
  {
    slug: 'qwen-image',
    title: 'Qwen-Image',
    org: '阿里巴巴通义千问',
    family: 'Qwen-Image',
    released: '2025-08-04',
    output: 'image',
    tags: ['MMDiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'MMDiT（Qwen2.5-VL 编码器）',
    params: '20.4B',
    repo: 'Qwen/Qwen-Image',
    summary: '阿里开源的 20B 文生图基座，复杂中英文字体渲染与图像编辑能力突出，发布后成为开源生图的事实标准之一。',
    links: {
      hf: 'https://huggingface.co/Qwen/Qwen-Image',
      github: 'https://github.com/QwenLM/Qwen-Image',
      paper: 'https://arxiv.org/abs/2508.02324',
    },
  },
  {
    slug: 'nextstep-1-large',
    title: 'NextStep-1-Large',
    org: '阶跃星辰 StepFun',
    family: 'NextStep',
    released: '2025-08-12',
    output: 'image',
    tags: ['自回归'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '自回归 Transformer + 流匹配头',
    params: '15.0B',
    repo: 'stepfun-ai/NextStep-1-Large',
    summary: '阶跃星辰的 14B 自回归图像生成模型，用连续图像 token 加流匹配头，把「自回归也能出高保真图」这条路走通了。',
    links: {
      hf: 'https://huggingface.co/stepfun-ai/NextStep-1-Large',
      github: 'https://github.com/stepfun-ai/NextStep-1',
      paper: 'https://arxiv.org/abs/2508.10711',
    },
  },
  {
    slug: 'qwen-image-edit',
    title: 'Qwen-Image-Edit',
    org: '阿里巴巴通义千问',
    family: 'Qwen-Image',
    released: '2025-08-18',
    output: 'image',
    tags: ['MMDiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'MMDiT（图像编辑）',
    params: '20.4B',
    repo: 'Qwen/Qwen-Image-Edit',
    summary: 'Qwen-Image 的官方编辑版本，支持语义与外观双重编辑、图中文字替换，是 2025 下半年使用最广的开源修图模型。',
    links: {
      hf: 'https://huggingface.co/Qwen/Qwen-Image-Edit',
      github: 'https://github.com/QwenLM/Qwen-Image',
      paper: 'https://arxiv.org/abs/2508.02324',
    },
  },
  {
    slug: 'hunyuanimage-2-1',
    title: 'HunyuanImage 2.1',
    org: '腾讯混元',
    family: 'HunyuanImage',
    released: '2025-09-08',
    output: 'image',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'Tencent Hunyuan Community License',
    architecture: '单双流混合 DiT（ByT5 + MLLM 双编码器）',
    params: '17B',
    repo: 'tencent/HunyuanImage-2.1',
    summary: '腾讯开源的 17B 原生 2K 文生图模型，用 32 倍压缩 VAE 与平均流蒸馏把 2K 出图成本压到消费级，中文文字渲染突出。',
    links: {
      hf: 'https://huggingface.co/tencent/HunyuanImage-2.1',
      github: 'https://github.com/Tencent-Hunyuan/HunyuanImage-2.1',
      paper: 'https://arxiv.org/abs/2509.04545',
    },
  },
  {
    slug: 'qwen-image-edit-2509',
    title: 'Qwen-Image-Edit-2509',
    org: '阿里巴巴通义千问',
    family: 'Qwen-Image',
    released: '2025-09-22',
    output: 'image',
    tags: ['MMDiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'MMDiT（多图输入编辑）',
    params: '20.4B',
    repo: 'Qwen/Qwen-Image-Edit-2509',
    summary: 'Qwen-Image-Edit 的 9 月迭代版，新增多图输入与更强一致性，人物合成与视角变换明显变好。',
    links: {
      hf: 'https://huggingface.co/Qwen/Qwen-Image-Edit-2509',
      github: 'https://github.com/QwenLM/Qwen-Image',
      paper: 'https://arxiv.org/abs/2508.02324',
    },
  },
  {
    slug: 'hunyuanimage-3-0',
    title: 'HunyuanImage 3.0',
    org: '腾讯混元',
    family: 'HunyuanImage',
    released: '2025-09-28',
    output: 'image',
    tags: ['自回归'],
    commercial: '有条件可商用',
    license: 'Tencent Hunyuan Community License',
    architecture: '原生多模态自回归 MoE Transformer（64 专家）',
    params: '83B（激活 13B）',
    repo: 'tencent/HunyuanImage-3.0',
    summary: '腾讯开源的 80B 自回归 MoE 生图模型，是目前体量最大的开源图像生成模型，用统一多模态路线逼近闭源质量。',
    links: {
      hf: 'https://huggingface.co/tencent/HunyuanImage-3.0',
      github: 'https://github.com/Tencent-Hunyuan/HunyuanImage-3.0',
      paper: 'https://arxiv.org/abs/2509.23951',
    },
  },
  {
    slug: 'lumina-dimoo',
    title: 'Lumina-DiMOO',
    org: '上海人工智能实验室 Alpha-VLLM',
    family: 'Lumina',
    released: '2025-10-08',
    output: 'image',
    tags: ['离散扩散'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '离散扩散多模态大模型（双向注意力并行解码）',
    params: '8.1B',
    repo: 'Alpha-VLLM/Lumina-DiMOO',
    summary: '上海 AI Lab 的离散扩散多模态大模型，用并行解码同时做文生图、图像编辑与图像理解，采样速度远超同规模自回归模型。',
    links: {
      hf: 'https://huggingface.co/Alpha-VLLM/Lumina-DiMOO',
      github: 'https://github.com/Alpha-VLLM/Lumina-DiMOO',
      paper: 'https://arxiv.org/abs/2510.06308',
    },
  },
  {
    slug: 'bria-fibo',
    title: 'Bria FIBO',
    org: 'Bria AI',
    family: 'FIBO',
    released: '2025-10-09',
    output: 'image',
    tags: ['DiT'],
    commercial: '不可商用',
    license: 'Bria FIBO License',
    architecture: 'DiT + Flow Matching（SmolLM3-3B 编码器）',
    params: '8.3B',
    repo: 'briaai/FIBO',
    summary: 'Bria 开源的 8B 文生图模型，首创 JSON 原生结构化提示控制，训练数据全部授权合规、可追溯。',
    links: {
      hf: 'https://huggingface.co/briaai/FIBO',
      paper: 'https://arxiv.org/abs/2511.06876',
    },
  },
  {
    slug: 'chronoedit-14b',
    title: 'ChronoEdit',
    org: 'NVIDIA',
    family: 'ChronoEdit',
    released: '2025-10-28',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '视频 DiT（把编辑当时间推理，14B）',
    params: '16.4B',
    repo: 'nvidia/ChronoEdit-14B-Diffusers',
    summary: 'NVIDIA 把图像编辑当成「时间推理」来做，移动物体、改变光照这类物理合理的编辑是它的强项，官方还附带放大 LoRA。',
    links: {
      hf: 'https://huggingface.co/nvidia/ChronoEdit-14B-Diffusers',
      github: 'https://github.com/nv-tlabs/ChronoEdit',
      paper: 'https://arxiv.org/abs/2510.04290',
    },
  },
  {
    slug: 'emu3-5-image',
    title: 'Emu3.5-Image',
    org: '北京智源研究院 BAAI',
    family: 'Emu3.5',
    released: '2025-10-31',
    output: 'image',
    tags: ['自回归'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '原生多模态自回归 Transformer（下一状态预测）',
    params: '34.1B',
    repo: 'BAAI/Emu3.5-Image',
    summary: '智源 Emu3.5 的图像生成权重，用「下一状态预测」的原生多模态路线做统一理解与生成，Apache-2.0 可直接商用。',
    links: {
      hf: 'https://huggingface.co/BAAI/Emu3.5-Image',
      github: 'https://github.com/baaivision/Emu3.5',
      paper: 'https://arxiv.org/abs/2510.26583',
    },
  },
  {
    slug: 'kandinsky-5-0-t2i-lite',
    title: 'Kandinsky 5.0 T2I Lite',
    org: 'Sber AI（Kandinsky Lab）',
    family: 'Kandinsky',
    released: '2025-11-20',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '潜在扩散 Transformer（Lite）',
    params: '2B',
    repo: 'kandinskylab/Kandinsky-5.0-T2I-Lite',
    summary: '俄罗斯 Sber 以 MIT 许可开源的轻量文生图权重，支持俄语与英语提示，是俄语区最重要的开源生图方案。',
    links: {
      hf: 'https://huggingface.co/kandinskylab/Kandinsky-5.0-T2I-Lite',
      github: 'https://github.com/ai-forever/Kandinsky-5',
      paper: 'https://arxiv.org/abs/2511.14993',
    },
  },
  {
    slug: 'z-image-turbo',
    title: 'Z-Image-Turbo',
    org: '阿里巴巴通义实验室',
    family: 'Z-Image',
    released: '2025-11-25',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '单流扩散 Transformer（S3-DiT）',
    params: '6.2B',
    repo: 'Tongyi-MAI/Z-Image-Turbo',
    summary: '阿里通义的 6B 单流 DiT 生图模型，8 步出图、16G 显存可跑，照片级真实感与中英文字渲染直逼闭源旗舰。',
    links: {
      hf: 'https://huggingface.co/Tongyi-MAI/Z-Image-Turbo',
      github: 'https://github.com/Tongyi-MAI/Z-Image',
      paper: 'https://arxiv.org/abs/2511.22699',
    },
  },
  {
    slug: 'flux-2-dev',
    title: 'FLUX.2 [dev]',
    org: 'Black Forest Labs',
    family: 'FLUX',
    released: '2025-11-25',
    output: 'image',
    tags: ['MMDiT'],
    commercial: '不可商用',
    license: 'FLUX.2 [dev] Non-Commercial License',
    architecture: '潜在流匹配 Rectified Flow Transformer（Mistral-3 24B 编码器）',
    params: '32.2B',
    repo: 'black-forest-labs/FLUX.2-dev',
    summary: 'BFL 的 32B 新一代图像模型，一套权重同时做文生图与最多 10 张参考图的多参考编辑，是当前能力最强的非商用开放权重生图模型。',
    links: {
      hf: 'https://huggingface.co/black-forest-labs/FLUX.2-dev',
      github: 'https://github.com/black-forest-labs/flux2',
    },
  },
  {
    slug: 'longcat-image',
    title: 'LongCat-Image',
    org: '美团 LongCat 团队',
    family: 'LongCat',
    released: '2025-12-08',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '扩散 Transformer（双语文字渲染）',
    params: '6B',
    repo: 'meituan-longcat/LongCat-Image',
    summary: '美团开源的 6B 中英双语文生图基座，汉字渲染覆盖度与写实度突出，用紧凑参数逼近大得多的模型。',
    links: {
      hf: 'https://huggingface.co/meituan-longcat/LongCat-Image',
      github: 'https://github.com/meituan-longcat/LongCat-Image',
      paper: 'https://arxiv.org/abs/2512.07584',
    },
  },
  {
    slug: 'longcat-image-edit',
    title: 'LongCat-Image-Edit',
    org: '美团 LongCat 团队',
    family: 'LongCat',
    released: '2025-12-08',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '扩散 Transformer（图像编辑）',
    params: '6B',
    repo: 'meituan-longcat/LongCat-Image-Edit',
    summary: 'LongCat-Image 的编辑版本，单图编辑的可控性与一致性在发布时登顶开源 SOTA，与生图基座一起以 Apache-2.0 开源。',
    links: {
      hf: 'https://huggingface.co/meituan-longcat/LongCat-Image-Edit',
      github: 'https://github.com/meituan-longcat/LongCat-Image',
      paper: 'https://arxiv.org/abs/2512.07584',
    },
  },
  {
    slug: 'qwen-image-layered',
    title: 'Qwen-Image-Layered',
    org: '阿里巴巴通义千问',
    family: 'Qwen-Image',
    released: '2025-12-19',
    output: 'image',
    tags: ['MMDiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'MMDiT（图层分解，多层 RGBA 输出）',
    params: '20.4B',
    repo: 'Qwen/Qwen-Image-Layered',
    summary: '阿里开源的图像分层模型，把一张图拆成多个 RGBA 图层分别编辑，用图层隔离从根上解决编辑一致性问题。',
    links: {
      hf: 'https://huggingface.co/Qwen/Qwen-Image-Layered',
      github: 'https://github.com/QwenLM/Qwen-Image',
      paper: 'https://arxiv.org/abs/2512.15603',
    },
  },
  {
    slug: 'qwen-image-edit-2511',
    title: 'Qwen-Image-Edit-2511',
    org: '阿里巴巴通义千问',
    family: 'Qwen-Image',
    released: '2025-12-23',
    output: 'image',
    tags: ['MMDiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'MMDiT（多图输入编辑）',
    params: '20.4B',
    repo: 'Qwen/Qwen-Image-Edit-2511',
    summary: 'Qwen-Image-Edit 的年末强化版，明显改善图像漂移与人物一致性，并把社区热门 LoRA 的能力内置进基座。',
    links: {
      hf: 'https://huggingface.co/Qwen/Qwen-Image-Edit-2511',
      github: 'https://github.com/QwenLM/Qwen-Image',
      paper: 'https://arxiv.org/abs/2508.02324',
    },
  },
  {
    slug: 'qwen-image-2512',
    title: 'Qwen-Image-2512',
    org: '阿里巴巴通义千问',
    family: 'Qwen-Image',
    released: '2025-12-31',
    output: 'image',
    tags: ['MMDiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'MMDiT（Qwen2.5-VL 编码器）',
    params: '20.4B',
    repo: 'Qwen/Qwen-Image-2512',
    summary: 'Qwen-Image 的 12 月更新版，削弱「AI 感」并提升人物质感与图文混排渲染，官方称其为当时最强的开源文生图模型。',
    links: {
      hf: 'https://huggingface.co/Qwen/Qwen-Image-2512',
      github: 'https://github.com/QwenLM/Qwen-Image',
      paper: 'https://arxiv.org/abs/2508.02324',
    },
  },

  /* ============================ 生图 · 2026 ============================ */
  {
    slug: 'glm-image',
    title: 'GLM-Image',
    org: '智谱 AI',
    family: 'GLM',
    released: '2026-01-08',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '自回归生成器 + 单流扩散解码器混合',
    params: '16B（9B 自回归 + 7B 扩散解码器）',
    repo: 'zai-org/GLM-Image',
    summary: '智谱以 MIT 许可开源的「自回归 + 扩散解码器」混合生图模型，长文本渲染与知识密集型出图明显更强。',
    links: {
      hf: 'https://huggingface.co/zai-org/GLM-Image',
      github: 'https://github.com/zai-org/GLM-Image',
    },
  },
  {
    slug: 'flux-2-klein-4b',
    title: 'FLUX.2 [klein] 4B',
    org: 'Black Forest Labs',
    family: 'FLUX',
    released: '2026-01-14',
    output: 'image',
    tags: ['MMDiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'Rectified Flow Transformer（klein 蒸馏版）',
    params: '3.9B',
    repo: 'black-forest-labs/FLUX.2-klein-4B',
    summary: 'BFL 把 FLUX.2 蒸馏到 4B 并以 Apache-2.0 放权重，让消费级显卡第一次能跑上这一代图像模型。',
    links: {
      hf: 'https://huggingface.co/black-forest-labs/FLUX.2-klein-4B',
      github: 'https://github.com/black-forest-labs/flux2',
    },
  },
  {
    slug: 'flux-2-klein-base-4b',
    title: 'FLUX.2 [klein] Base 4B',
    org: 'Black Forest Labs',
    family: 'FLUX',
    released: '2026-01-14',
    output: 'image',
    tags: ['MMDiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'Rectified Flow Transformer（未蒸馏基座）',
    params: '3.9B',
    repo: 'black-forest-labs/FLUX.2-klein-base-4B',
    summary: 'FLUX.2 klein 的未蒸馏基座版本，专为微调与训练流程准备，同样是 Apache-2.0。',
    links: {
      hf: 'https://huggingface.co/black-forest-labs/FLUX.2-klein-base-4B',
      github: 'https://github.com/black-forest-labs/flux2',
    },
  },
  {
    slug: 'flux-2-klein-9b',
    title: 'FLUX.2 [klein] 9B',
    org: 'Black Forest Labs',
    family: 'FLUX',
    released: '2026-01-14',
    output: 'image',
    tags: ['MMDiT'],
    commercial: '不可商用',
    license: 'FLUX.2 [klein] Non-Commercial License',
    architecture: 'Rectified Flow Transformer（klein 蒸馏版）',
    params: '9.1B',
    repo: 'black-forest-labs/FLUX.2-klein-9B',
    summary: 'klein 系列里画质更高的一档，9B 权重沿用非商用许可，适合研究与非商业创作。',
    links: {
      hf: 'https://huggingface.co/black-forest-labs/FLUX.2-klein-9B',
      github: 'https://github.com/black-forest-labs/flux2',
    },
  },
  {
    slug: 'z-image',
    title: 'Z-Image',
    org: '阿里巴巴通义实验室',
    family: 'Z-Image',
    released: '2026-01-23',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '单流扩散 Transformer（S3-DiT）',
    params: '6.2B',
    repo: 'Tongyi-MAI/Z-Image',
    summary: 'Z-Image 的基座版本，比 Turbo 更耐调、更适合继续微调，同样以 Apache-2.0 开源。',
    links: {
      hf: 'https://huggingface.co/Tongyi-MAI/Z-Image',
      github: 'https://github.com/Tongyi-MAI/Z-Image',
      paper: 'https://arxiv.org/abs/2511.22699',
    },
  },
  {
    slug: 'hunyuanimage-3-0-instruct',
    title: 'HunyuanImage 3.0-Instruct',
    org: '腾讯混元',
    family: 'HunyuanImage',
    released: '2026-01-26',
    output: 'image',
    tags: ['自回归'],
    commercial: '有条件可商用',
    license: 'Tencent Hunyuan Community License',
    architecture: '原生多模态自回归 MoE Transformer（指令编辑）',
    params: '83B（激活 13B）',
    repo: 'tencent/HunyuanImage-3.0-Instruct',
    summary: 'HunyuanImage 3.0 的指令编辑版本，把 80B 自回归生图模型接上对话式修图能力。',
    links: {
      hf: 'https://huggingface.co/tencent/HunyuanImage-3.0-Instruct',
      github: 'https://github.com/Tencent-Hunyuan/HunyuanImage-3.0',
    },
  },
  {
    slug: 'longcat-image-edit-turbo',
    title: 'LongCat-Image-Edit-Turbo',
    org: '美团 LongCat 团队',
    family: 'LongCat',
    released: '2026-02-03',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '扩散 Transformer（少步蒸馏编辑）',
    params: '6B',
    repo: 'meituan-longcat/LongCat-Image-Edit-Turbo',
    summary: 'LongCat-Image-Edit 的少步加速版，把修图推理压到几步，Apache-2.0 且适合本地批量处理。',
    links: {
      hf: 'https://huggingface.co/meituan-longcat/LongCat-Image-Edit-Turbo',
      github: 'https://github.com/meituan-longcat/LongCat-Image',
    },
  },
  {
    slug: 'ernie-image-turbo',
    title: 'ERNIE-Image-Turbo',
    org: '百度',
    family: 'ERNIE-Image',
    released: '2026-04-02',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '扩散 Transformer（少步版本）',
    params: '8.0B',
    repo: 'baidu/ERNIE-Image-Turbo',
    summary: '百度 ERNIE-Image 的少步版本，8B 权重以 Apache-2.0 开源，主打中文场景与快速出图。',
    links: {
      hf: 'https://huggingface.co/baidu/ERNIE-Image-Turbo',
      github: 'https://github.com/baidu/ernie-image',
    },
  },
  {
    slug: 'ernie-image',
    title: 'ERNIE-Image',
    org: '百度',
    family: 'ERNIE-Image',
    released: '2026-04-07',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '扩散 Transformer',
    params: '8.0B',
    repo: 'baidu/ERNIE-Image',
    summary: '百度开源的 8B 文生图基座，中文提示与汉字排版是强项，和 Turbo 版一起构成 ERNIE-Image 家族。',
    links: {
      hf: 'https://huggingface.co/baidu/ERNIE-Image',
      github: 'https://github.com/baidu/ernie-image',
    },
  },
  {
    slug: 'hidream-o1-image',
    title: 'HiDream-O1-Image',
    org: 'HiDream.ai 智象未来',
    family: 'HiDream',
    released: '2026-05-08',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '扩散 Transformer（图像与文本双输入）',
    params: '8.8B',
    repo: 'HiDream-ai/HiDream-O1-Image',
    summary: 'HiDream 的 O1 系列图像模型，8.8B 参数兼顾文生图与参考图编辑，继续以 MIT 许可开放。',
    links: {
      hf: 'https://huggingface.co/HiDream-ai/HiDream-O1-Image',
      github: 'https://github.com/HiDream-ai/HiDream-O1-Image',
    },
  },
  {
    slug: 'lance',
    title: 'Lance',
    org: '字节跳动 research',
    family: 'Lance',
    released: '2026-05-15',
    output: 'image',
    tags: ['自回归'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '统一多模态 Transformer（多任务协同，图像 + 视频）',
    params: '3B',
    repo: 'bytedance-research/Lance',
    summary: '字节的轻量统一多模态模型，一套权重同时做图像与视频的理解、生成和编辑，把「统一」做到了 3B 量级。',
    links: {
      hf: 'https://huggingface.co/bytedance-research/Lance',
      github: 'https://github.com/bytedance/Lance',
    },
  },
  {
    slug: 'ernie-image-aes',
    title: 'ERNIE-Image-Aes',
    org: '百度',
    family: 'ERNIE-Image',
    released: '2026-05-18',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '扩散 Transformer（美学偏好微调）',
    params: '7.9B',
    repo: 'baidu/ERNIE-Image-Aes',
    summary: 'ERNIE-Image 的美学偏好版本，把出图口味往「好看」上调，用来做风格化内容更省提示词功夫。',
    links: {
      hf: 'https://huggingface.co/baidu/ERNIE-Image-Aes',
      github: 'https://github.com/baidu/ernie-image',
    },
  },
  {
    slug: 'cosmos3-super-text2image',
    title: 'Cosmos3-Super-Text2Image',
    org: 'NVIDIA',
    family: 'Cosmos',
    released: '2026-05-28',
    output: 'image',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'NVIDIA Open Model License',
    architecture: '全模态世界模型（64.6B）',
    params: '64.6B',
    repo: 'nvidia/Cosmos3-Super-Text2Image',
    summary: 'NVIDIA Cosmos 3 世界模型平台的文生图入口，64.6B 参数面向物理 AI 场景，许可为 NVIDIA 开放模型协议。',
    links: {
      hf: 'https://huggingface.co/nvidia/Cosmos3-Super-Text2Image',
      github: 'https://github.com/nvidia/cosmos',
    },
  },
  {
    slug: 'sensenova-u1-5-8b-mot',
    title: 'SenseNova-U1.5-8B-MoT',
    org: '商汤科技 SenseNova',
    family: 'SenseNova U',
    released: '2026-08-19',
    output: 'image',
    tags: ['自回归'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'NEO-unify 统一多模态 MoT（8B）',
    params: '17.5B',
    repo: 'sensenova/SenseNova-U1.5-8B-MoT',
    summary: '商汤的统一多模态模型 U1.5，理解与生成共用一套 MoT 主干，Apache-2.0 且带完整的中文文档。',
    links: {
      hf: 'https://huggingface.co/sensenova/SenseNova-U1.5-8B-MoT',
      github: 'https://github.com/OpenSenseNova/SenseNova-U1',
    },
  },
  {
    slug: 'llada-image',
    title: 'LLaDA-Image',
    org: '蚂蚁集团 inclusionAI',
    family: 'LLaDA',
    released: '2026-08-28',
    output: 'image',
    tags: ['离散扩散'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '离散扩散统一模型（文生图 + 编辑）',
    params: '6.5B',
    repo: 'inclusionAI/LLaDA-Image',
    summary: '蚂蚁的离散扩散图像模型，连训练配方一起开源，文生图与编辑共用一套权重。',
    links: {
      hf: 'https://huggingface.co/inclusionAI/LLaDA-Image',
      github: 'https://github.com/inclusionAI/LLaDA-Image',
      paper: 'https://arxiv.org/pdf/2609.03796',
    },
  },
  {
    slug: 'internlumina-u2',
    title: 'InternLumina-U2',
    org: '上海人工智能实验室 InternLM',
    family: 'InternLumina',
    released: '2026-09-01',
    output: 'image',
    tags: ['离散扩散'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '多码本扩散大语言模型（MoE 16B-A1B）',
    params: '16B（激活 1B）',
    repo: 'internlm/InternLumina-U2',
    summary: '上海 AI Lab 的多码本扩散大模型，用 1B 激活参数一起做图像生成、编辑、视频与 3D 理解。',
    links: {
      hf: 'https://huggingface.co/internlm/InternLumina-U2',
      github: 'https://github.com/InternLM/InternLumina-U2',
    },
  },
  {
    slug: 'qwen-image-2-1',
    title: 'Qwen-Image-2.1',
    org: '阿里巴巴通义千问',
    family: 'Qwen-Image',
    released: '2026-09-14',
    output: 'image',
    tags: ['DiT'],
    commercial: '不可商用',
    license: 'Qwen Research License',
    architecture: '单流 DiT（32 层，生成与编辑统一）',
    params: '7B',
    repo: 'Qwen/Qwen-Image-2.1',
    summary: 'Qwen-Image 的第二代，把生成与编辑统一进 7B 的 32 层单流 DiT，能原生出透明通道图，但许可是研究用途。',
    links: {
      hf: 'https://huggingface.co/Qwen/Qwen-Image-2.1',
      github: 'https://github.com/QwenLM/Qwen-Image-2.1',
    },
  },
  {
    slug: 'skywork-unipic3',
    title: 'Skywork UniPic3',
    org: '昆仑万维 Skywork',
    family: 'Skywork UniPic',
    released: '2026-01-13',
    output: 'image',
    tags: ['自回归'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '统一多模态 Transformer（流匹配，多图条件）',
    params: '2B',
    repo: 'Skywork/Unipic3',
    summary: 'UniPic 系列的新一代统一模型，支持单图编辑与 2～6 张多图合成，继续以 MIT 许可开放。',
    links: {
      hf: 'https://huggingface.co/Skywork/Unipic3',
      github: 'https://github.com/SkyworkAI/UniPic',
      paper: 'https://arxiv.org/abs/2601.15664',
    },
  },
  {
    slug: 'firered-image-edit-1-0',
    title: 'FireRed-Image-Edit 1.0',
    org: '小红书 FireRed 团队',
    family: 'FireRed',
    released: '2026-02-14',
    output: 'image',
    tags: ['MMDiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '图像编辑 DiT（20B，原生编辑能力）',
    params: '20.4B',
    repo: 'FireRedTeam/FireRed-Image-Edit-1.0',
    summary: '小红书开源的 20B 通用图像编辑模型，在 ImgEdit 榜单上超过同期开源模型，文字风格保持与老照片修复是它的强项。',
    links: {
      hf: 'https://huggingface.co/FireRedTeam/FireRed-Image-Edit-1.0',
      github: 'https://github.com/FireRedTeam/FireRed-Image-Edit',
    },
  },
  {
    slug: 'firered-image-edit-1-1',
    title: 'FireRed-Image-Edit 1.1',
    org: '小红书 FireRed 团队',
    family: 'FireRed',
    released: '2026-03-02',
    output: 'image',
    tags: ['MMDiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '图像编辑 DiT（20B，强化身份一致性与多图条件）',
    params: '20.4B',
    repo: 'FireRedTeam/FireRed-Image-Edit-1.1',
    summary: 'FireRed-Image-Edit 的 1.1 版，人物身份一致性、多元素融合与妆造文本参考达到开源 SOTA，并配套 ComfyUI 与量化部署。',
    links: {
      hf: 'https://huggingface.co/FireRedTeam/FireRed-Image-Edit-1.1',
      github: 'https://github.com/FireRedTeam/FireRed-Image-Edit',
      paper: 'https://arxiv.org/abs/2602.13344',
    },
  },
  {
    slug: 'nucleus-image',
    title: 'Nucleus-Image',
    org: 'Nucleus AI',
    family: 'Nucleus',
    released: '2026-03-17',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '稀疏 MoE 扩散 Transformer（32 层，每层 64 路由专家）',
    params: '16.9B（激活约 2B）',
    repo: 'NucleusAI/Nucleus-Image',
    summary: '完全开源的稀疏 MoE 扩散模型，17B 总参数只激活约 2B 就追平 Qwen-Image 这一档，权重、训练代码与数据一起开放。',
    links: {
      hf: 'https://huggingface.co/NucleusAI/Nucleus-Image',
      github: 'https://github.com/WithNucleusAI/Nucleus-Image',
      paper: 'https://arxiv.org/abs/2604.12163',
    },
  },
  {
    slug: 'joyai-image-edit',
    title: 'JoyAI-Image-Edit',
    org: '京东 jd-opensource',
    family: 'JoyAI',
    released: '2026-03-31',
    output: 'image',
    tags: ['MMDiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '统一多模态编辑基础模型（空间理解导向）',
    params: '16B',
    repo: 'jdopensource/JoyAI-Image-Edit',
    summary: '京东开源的空间智能图像编辑模型，支持物体移动、物体旋转与相机视角控制三类空间编辑指令。',
    links: {
      hf: 'https://huggingface.co/jdopensource/JoyAI-Image-Edit',
      github: 'https://github.com/jd-opensource/JoyAI-Image',
      paper: 'https://arxiv.org/abs/2605.04128',
    },
  },
  {
    slug: 'sensenova-u1-8b-mot',
    title: 'SenseNova-U1-8B-MoT',
    org: '商汤科技 SenseNova',
    family: 'SenseNova U',
    released: '2026-04-27',
    output: 'image',
    tags: ['自回归'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'NEO-unify 原生多模态 MoT（无视觉编码器、无 VAE）',
    params: '17.6B',
    repo: 'sensenova/SenseNova-U1-8B-MoT',
    summary: '商汤的原生统一多模态模型，去掉视觉编码器与 VAE，在单一架构里同时做图像理解、文生图与指令编辑。',
    links: {
      hf: 'https://huggingface.co/sensenova/SenseNova-U1-8B-MoT',
      github: 'https://github.com/OpenSenseNova/SenseNova-U1',
      paper: 'https://arxiv.org/abs/2605.12500',
    },
  },
  {
    slug: 'sensenova-u1-a3b-mot',
    title: 'SenseNova-U1-A3B-MoT',
    org: '商汤科技 SenseNova',
    family: 'SenseNova U',
    released: '2026-05-08',
    output: 'image',
    tags: ['自回归'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'NEO-unify 原生多模态 MoT（MoE 主干）',
    params: '38.7B（激活约 3B）',
    repo: 'sensenova/SenseNova-U1-A3B-MoT',
    summary: 'SenseNova-U1 的 MoE 主干版本，用稀疏激活把统一理解与生成的推理成本压下来。',
    links: {
      hf: 'https://huggingface.co/sensenova/SenseNova-U1-A3B-MoT',
      github: 'https://github.com/OpenSenseNova/SenseNova-U1',
      paper: 'https://arxiv.org/abs/2605.12500',
    },
  },
  {
    slug: 'nl-diffusion-image',
    title: 'Nemotron-Labs-Diffusion-Image',
    org: 'NVIDIA',
    family: 'Nemotron-Labs',
    released: '2026-06-03',
    output: 'image',
    tags: ['离散扩散'],
    commercial: '不可商用',
    license: 'NVIDIA OneWay Noncommercial License',
    architecture: '掩码离散扩散 Transformer（Emu3.5 离散 tokenizer）',
    params: '11.9B',
    repo: 'nvidia/NL-Diffusion-Image',
    summary: '英伟达把掩码离散扩散用到高分辨率文生图上，8B 规模在 GenEval 上做到 0.90，但只授权研究与评估用途。',
    links: {
      hf: 'https://huggingface.co/nvidia/NL-Diffusion-Image',
      paper: 'https://arxiv.org/abs/2606.29814',
    },
  },
  {
    slug: 'krea-2',
    title: 'Krea 2',
    org: 'Krea',
    family: 'Krea',
    released: '2026-06-18',
    output: 'image',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'Krea 2 自定义许可',
    architecture: '流匹配扩散 Transformer（Raw 基座 + Turbo 蒸馏版）',
    params: '12.8B',
    repo: 'krea/Krea-2-Raw',
    summary: '设计工具公司 Krea 首次放出自己的文生图权重，Raw 与 Turbo 双版本同时上线，审美取向偏商业设计。',
    links: {
      hf: 'https://huggingface.co/krea/Krea-2-Raw',
    },
  },
  {
    slug: 'sensenova-vision-7b-mot',
    title: 'SenseNova-Vision-7B-MoT',
    org: '商汤科技 SenseNova',
    family: 'SenseNova U',
    released: '2026-06-29',
    output: 'image',
    tags: ['自回归'],
    commercial: '不可商用',
    license: 'CC-BY-NC-4.0',
    architecture: 'NEO-unify 统一多模态 MoT（生成 + 稠密感知）',
    params: '7B',
    repo: 'sensenova/SenseNova-Vision-7B-MoT',
    summary: '商汤的视觉中心统一模型，同一架构里兼顾图像生成、编辑与深度、分割等稠密感知，但许可是非商用。',
    links: {
      hf: 'https://huggingface.co/sensenova/SenseNova-Vision-7B-MoT',
      github: 'https://github.com/OpenSenseNova/SenseNova-U1',
      paper: 'https://arxiv.org/abs/2607.06560',
    },
  },
  {
    slug: 'mage-flow',
    title: 'Mage-Flow',
    org: 'Microsoft',
    family: 'Mage',
    released: '2026-07-21',
    output: 'image',
    tags: ['MMDiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '原生分辨率多模态扩散 Transformer（NR-MMDiT）',
    params: '4B',
    repo: 'microsoft/Mage-Flow',
    summary: '微软的 4B 原生分辨率生图基座，A100 上 0.59 秒出一张 1024²，用四分之一规模逼近 32B 级模型的质量。',
    links: {
      hf: 'https://huggingface.co/microsoft/Mage-Flow',
      github: 'https://github.com/microsoft/Mage',
      paper: 'https://arxiv.org/abs/2607.19064',
    },
  },
  {
    slug: 'mage-flow-edit',
    title: 'Mage-Flow-Edit',
    org: 'Microsoft',
    family: 'Mage',
    released: '2026-07-21',
    output: 'image',
    tags: ['MMDiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '原生分辨率多模态扩散 Transformer（图像-文本联合条件）',
    params: '4B',
    repo: 'microsoft/Mage-Flow-Edit',
    summary: 'Mage-Flow 家族的指令编辑成员，1024² 编辑一次约 1 秒，是目前最快的高分辨率开源编辑模型之一。',
    links: {
      hf: 'https://huggingface.co/microsoft/Mage-Flow-Edit',
      github: 'https://github.com/microsoft/Mage',
      paper: 'https://arxiv.org/abs/2607.19064',
    },
  },
  {
    slug: 'ming-image-0-1-design',
    title: 'Ming-Image-0.1-Design',
    org: '蚂蚁集团 inclusionAI',
    family: 'Ming',
    released: '2026-09-17',
    output: 'image',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '扩散 Transformer（文本密集版式）',
    params: '6.2B',
    repo: 'inclusionAI/Ming-Image-0.1-Design',
    summary: '蚂蚁开源的 6B 设计向生图模型，专攻 UI、信息图与海报这类文字密集版式，并支持 RGBA 透明底输出。',
    links: {
      hf: 'https://huggingface.co/inclusionAI/Ming-Image-0.1-Design',
      github: 'https://github.com/inclusionAI/Ming-Image',
    },
  },

  /* ============================ 生视频 · 2025 ============================ */
  {
    slug: 'cosmos-1-0-diffusion-7b',
    title: 'Cosmos-1.0-Diffusion-7B',
    org: 'NVIDIA',
    family: 'Cosmos',
    released: '2025-01-07',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'NVIDIA Open Model License',
    architecture: '扩散世界模型（Text2World）',
    params: '7B',
    repo: 'nvidia/Cosmos-1.0-Diffusion-7B-Text2World',
    summary: 'NVIDIA 世界基础模型平台的第一代扩散模型，把「按文字生成可交互世界」做成了开放权重的一整套工具链。',
    links: {
      hf: 'https://huggingface.co/nvidia/Cosmos-1.0-Diffusion-7B-Text2World',
      github: 'https://github.com/nvidia-cosmos/cosmos-predict1',
    },
  },
  {
    slug: 'step-video-t2v',
    title: 'Step-Video-T2V',
    org: '阶跃星辰 StepFun',
    family: 'Step',
    released: '2025-02-17',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: 'DiT（视频 VAE + 双向注意力）',
    params: '29.3B',
    repo: 'stepfun-ai/stepvideo-t2v',
    summary: '阶跃星辰开源的 30B 文生视频模型，发布时是参数规模最大的开源视频模型，MIT 许可让商用没有后顾之忧。',
    links: {
      hf: 'https://huggingface.co/stepfun-ai/stepvideo-t2v',
      github: 'https://github.com/stepfun-ai/Step-Video-T2V',
      paper: 'https://arxiv.org/abs/2502.10248',
    },
  },
  {
    slug: 'wan2-1-t2v-14b',
    title: 'Wan2.1 T2V 14B',
    org: '阿里巴巴通义万相',
    family: 'Wan',
    released: '2025-02-25',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'DiT（视频扩散 + 轻量 VAE）',
    params: '14.3B',
    repo: 'Wan-AI/Wan2.1-T2V-14B',
    summary: '阿里万相的 14B 文生视频模型，用 Apache-2.0 开放权重，是 2025 年开源视频生态里被复用最多的一套底座。',
    links: {
      hf: 'https://huggingface.co/Wan-AI/Wan2.1-T2V-14B',
      github: 'https://github.com/Wan-Video/Wan2.1',
    },
  },
  {
    slug: 'wan2-1-t2v-1-3b',
    title: 'Wan2.1 T2V 1.3B',
    org: '阿里巴巴通义万相',
    family: 'Wan',
    released: '2025-02-25',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'DiT（轻量版）',
    params: '1.4B',
    repo: 'Wan-AI/Wan2.1-T2V-1.3B',
    vram: '8G 显存可跑 480P',
    summary: '同批放出的 1.3B 小模型，8G 显存的消费级显卡就能出 480P 视频，把视频生成的门槛真正拉了下来。',
    links: {
      hf: 'https://huggingface.co/Wan-AI/Wan2.1-T2V-1.3B',
      github: 'https://github.com/Wan-Video/Wan2.1',
    },
  },
  {
    slug: 'wan2-1-i2v-14b',
    title: 'Wan2.1 I2V 14B',
    org: '阿里巴巴通义万相',
    family: 'Wan',
    released: '2025-02-25',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'DiT（图生视频）',
    params: '16.4B',
    repo: 'Wan-AI/Wan2.1-I2V-14B-720P',
    summary: 'Wan2.1 的图生视频版本，720P 权重让「一张照片动起来」第一次有了可商用的开源方案。',
    links: {
      hf: 'https://huggingface.co/Wan-AI/Wan2.1-I2V-14B-720P',
      github: 'https://github.com/Wan-Video/Wan2.1',
    },
  },
  {
    slug: 'echovideo',
    title: 'EchoVideo',
    org: '字节跳动 ByteDance',
    family: 'EchoVideo',
    released: '2025-02-27',
    output: 'video',
    tags: ['DiT'],
    commercial: '不可商用',
    license: 'CC BY-NC 4.0',
    architecture: 'DiT + 多模态特征融合（基于 CogVideoX-5B 主干）',
    params: '5B',
    repo: 'bytedance-research/EchoVideo',
    summary: '字节开源的身份保持人像视频模型，一张照片加文本就能生成人物视频，重点解决语义冲突与生硬贴脸。',
    links: {
      hf: 'https://huggingface.co/bytedance-research/EchoVideo',
      github: 'https://github.com/bytedance/EchoVideo',
      paper: 'https://arxiv.org/abs/2501.13452',
    },
  },
  {
    slug: 'open-sora-2-0',
    title: 'Open-Sora 2.0',
    org: 'HPC-AI Tech',
    family: 'Open-Sora',
    released: '2025-03-04',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'DiT + 3D 全注意力',
    params: '11B',
    repo: 'hpcai-tech/Open-Sora-v2',
    summary: '以约 20 万美元成本训练出的 11B 开源视频模型，一套权重同时覆盖文生与图生视频，把 Sora 级效果的成本门槛压了下来。',
    links: {
      hf: 'https://huggingface.co/hpcai-tech/Open-Sora-v2',
      github: 'https://github.com/hpcaitech/Open-Sora',
      paper: 'https://arxiv.org/abs/2503.09642',
    },
  },
  {
    slug: 'hunyuanvideo-i2v',
    title: 'HunyuanVideo-I2V',
    org: '腾讯混元',
    family: 'Hunyuan',
    released: '2025-03-06',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'Tencent Hunyuan Community License',
    architecture: 'DiT（图生视频）',
    params: '13B',
    repo: 'tencent/HunyuanVideo-I2V',
    summary: '腾讯把 HunyuanVideo 补上图生视频能力，同时给出角色参考与镜头控制示例，是当时中文场景最好用的开源视频模型。',
    links: {
      hf: 'https://huggingface.co/tencent/HunyuanVideo-I2V',
      github: 'https://github.com/Tencent-Hunyuan/HunyuanVideo-I2V',
      paper: 'https://arxiv.org/abs/2503.06704',
    },
  },
  {
    slug: 'step-video-ti2v',
    title: 'Step-Video-TI2V',
    org: '阶跃星辰 StepFun',
    family: 'Step',
    released: '2025-03-17',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: 'DiT（文生 + 图生视频统一）',
    params: '29.4B',
    repo: 'stepfun-ai/stepvideo-ti2v',
    summary: 'Step-Video 的图生视频版本，30B 权重继续以 MIT 开放，镜头运动与物理一致性在当时属第一梯队。',
    links: {
      hf: 'https://huggingface.co/stepfun-ai/stepvideo-ti2v',
      github: 'https://github.com/stepfun-ai/Step-Video-TI2V',
      paper: 'https://arxiv.org/abs/2503.10215',
    },
  },
  {
    slug: 'vace-wan2-1-1-3b',
    title: 'VACE（Wan2.1 1.3B 预览版）',
    org: '阿里巴巴 ali-vilab',
    family: 'VACE',
    released: '2025-04-01',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'DiT + 统一控制模块',
    params: '2.2B',
    repo: 'ali-vilab/VACE-Wan2.1-1.3B-Preview',
    summary: '阿里 VACE 把参考图、遮罩、姿态、深度等控制信号统一成一套视频编辑接口，先放 1.3B 预览权重试水。',
    links: {
      hf: 'https://huggingface.co/ali-vilab/VACE-Wan2.1-1.3B-Preview',
      github: 'https://github.com/ali-vilab/VACE',
      paper: 'https://arxiv.org/abs/2503.07598',
    },
  },
  {
    slug: 'magi-1',
    title: 'MAGI-1',
    org: 'Sand.ai',
    family: 'MAGI',
    released: '2025-04-21',
    output: 'video',
    tags: ['自回归'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '自回归分块扩散 Transformer',
    params: '24B',
    repo: 'sand-ai/MAGI-1',
    summary: 'Sand.ai 的 24B 视频模型，用自回归分块生成做到「边生成边播放」，把可控性与长视频续写带进开源方案。',
    links: {
      hf: 'https://huggingface.co/sand-ai/MAGI-1',
      github: 'https://github.com/SandAI-org/MAGI-1',
    },
  },
  {
    slug: 'skyreels-v2',
    title: 'SkyReels V2',
    org: '昆仑万维 Skywork',
    family: 'SkyReels',
    released: '2025-04-21',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'Skywork 模型社区许可协议',
    architecture: 'DiT + 扩散强迫（Diffusion Forcing）',
    params: '14.3B',
    repo: 'Skywork/SkyReels-V2-T2V-14B-720P',
    summary: '昆仑万维的开源视频模型，用扩散强迫把长视频的一致性做上去，540P / 720P 与 1.3B / 14B 一并放出。',
    links: {
      hf: 'https://huggingface.co/Skywork/SkyReels-V2-T2V-14B-720P',
      github: 'https://github.com/SkyworkAI/SkyReels-V2',
      paper: 'https://arxiv.org/abs/2504.13074',
    },
  },
  {
    slug: 'wan2-1-flf2v-14b',
    title: 'Wan2.1-FLF2V-14B',
    org: '阿里巴巴通义万相',
    family: 'Wan',
    released: '2025-04-17',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'DiT（首尾帧生视频）',
    params: '14B',
    repo: 'Wan-AI/Wan2.1-FLF2V-14B-720P',
    summary: 'Wan2.1 的首尾帧生视频模型，给定首帧与尾帧就能补出连贯过渡，中文提示词场景优化得比较到位。',
    links: {
      hf: 'https://huggingface.co/Wan-AI/Wan2.1-FLF2V-14B-720P',
      github: 'https://github.com/Wan-Video/Wan2.1',
    },
  },
  {
    slug: 'cosmos-predict2',
    title: 'Cosmos-Predict2',
    org: 'NVIDIA',
    family: 'Cosmos',
    released: '2025-04-25',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'NVIDIA Open Model License',
    architecture: '扩散世界模型（Video2World / Text2Image）',
    params: '2B / 14B',
    repo: 'nvidia/Cosmos-Predict2-2B-Video2World',
    summary: 'Cosmos 的第二代预测模型，2B 与 14B 两档同时覆盖视频生成与世界状态预测。',
    links: {
      hf: 'https://huggingface.co/nvidia/Cosmos-Predict2-2B-Video2World',
      github: 'https://github.com/nvidia-cosmos/cosmos-predict2',
    },
  },
  {
    slug: 'matrix-game',
    title: 'Matrix-Game',
    org: '昆仑万维 Skywork',
    family: 'Matrix-Game',
    released: '2025-05-07',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '交互式世界模型 DiT',
    repo: 'Skywork/Matrix-Game',
    summary: '昆仑万维开源的交互式世界模型，用键盘鼠标信号实时驱动画面，是「可玩的开源世界模型」第一批尝试。',
    links: {
      hf: 'https://huggingface.co/Skywork/Matrix-Game',
      github: 'https://github.com/SkyworkAI/Matrix-Game',
    },
  },
  {
    slug: 'hunyuan-custom',
    title: 'HunyuanCustom',
    org: '腾讯混元',
    family: 'Hunyuan',
    released: '2025-05-08',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'Tencent Hunyuan Community License',
    architecture: 'DiT（多模态条件定制）',
    params: '13B',
    repo: 'tencent/HunyuanCustom',
    summary: '腾讯混元的定制化视频模型，支持主体保持、身份参考与音频驱动，把「让指定的人或物动起来」做成开源能力。',
    links: {
      hf: 'https://huggingface.co/tencent/HunyuanCustom',
      github: 'https://github.com/Tencent-Hunyuan/HunyuanCustom',
      paper: 'https://arxiv.org/abs/2505.04512',
    },
  },
  {
    slug: 'wan2-1-vace-14b',
    title: 'Wan2.1-VACE-14B',
    org: '阿里巴巴通义万相',
    family: 'Wan',
    released: '2025-05-14',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'DiT + 统一控制模块',
    params: '17.3B',
    repo: 'Wan-AI/Wan2.1-VACE-14B',
    summary: 'VACE 的 14B 正式版本，把参考、遮罩与控制信号统一到 Wan2.1 上，是当时最通用的开源视频编辑底座。',
    links: {
      hf: 'https://huggingface.co/Wan-AI/Wan2.1-VACE-14B',
      github: 'https://github.com/ali-vilab/VACE',
      paper: 'https://arxiv.org/abs/2503.07598',
    },
  },
  {
    slug: 'ltx-video-0-9-5',
    title: 'LTX-Video 0.9.5',
    org: 'Lightricks',
    family: 'LTX',
    released: '2025-03-16',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Open RAIL-M',
    architecture: 'DiT（高压缩 VAE，实时生成）',
    params: '2B',
    repo: 'Lightricks/LTX-Video-0.9.5',
    summary: 'Lightricks 的 LTX-Video 首版实时模型，30FPS 下生成速度快于播放速度，2B 权重配 Open RAIL-M 可直接商用。',
    links: {
      hf: 'https://huggingface.co/Lightricks/LTX-Video',
      github: 'https://github.com/Lightricks/LTX-Video',
      paper: 'https://arxiv.org/abs/2412.09545',
    },
  },
  {
    slug: 'hunyuanvideo-avatar',
    title: 'HunyuanVideo-Avatar',
    org: '腾讯混元',
    family: 'Hunyuan',
    released: '2025-05-26',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'Tencent Hunyuan Community License',
    architecture: 'DiT（音频驱动数字人）',
    params: '13B',
    repo: 'tencent/HunyuanVideo-Avatar',
    summary: '腾讯开源的音频驱动数字人模型，一张图加一段音频就能出口型同步的说话视频，支持多角色对话。',
    links: {
      hf: 'https://huggingface.co/tencent/HunyuanVideo-Avatar',
      github: 'https://github.com/Tencent-Hunyuan/HunyuanVideo-Avatar',
      paper: 'https://arxiv.org/abs/2505.20156',
    },
  },
  {
    slug: 'phantom-wan-14b',
    title: 'Phantom-Wan-14B',
    org: '字节跳动 ByteDance',
    family: 'Phantom',
    released: '2025-05-27',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'DiT + 跨模态对齐（基于 Wan2.1 的主体参考生视频）',
    params: '14B',
    repo: 'bytedance-research/Phantom',
    summary: '字节把 Phantom 的主体一致性框架移植到 Wan2.1 上，单张或多张参考图就能生成主体一致的视频。',
    links: {
      hf: 'https://huggingface.co/bytedance-research/Phantom',
      github: 'https://github.com/Phantom-video/Phantom',
      paper: 'https://arxiv.org/abs/2502.11079',
    },
  },
  {
    slug: 'ltx-video-0-9-8',
    title: 'LTX-Video 0.9.8',
    org: 'Lightricks',
    family: 'LTX',
    released: '2025-07-16',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'LTX-Video Open Weights License',
    architecture: 'DiT（0.9.8 主干 + 蒸馏加速）',
    params: '13B',
    repo: 'Lightricks/LTX-Video-0.9.8-13B-distilled',
    summary: 'LTX-Video 的 0.9.8 版，画质与运动稳定性继续提升，蒸馏版几步就能出片。',
    links: {
      hf: 'https://huggingface.co/Lightricks/LTX-Video-0.9.8-13B-distilled',
      github: 'https://github.com/Lightricks/LTX-Video',
    },
  },
  {
    slug: 'wan2-2-t2v-a14b',
    title: 'Wan2.2 T2V A14B',
    org: '阿里巴巴通义万相',
    family: 'Wan',
    released: '2025-07-28',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'MoE DiT（高噪 / 低噪双专家）',
    params: '27B（激活 14B）',
    repo: 'Wan-AI/Wan2.2-T2V-A14B',
    summary: 'Wan2.2 的文生视频版本，用 MoE 把「高画质」和「低显存」拆成两个专家，电影感美学是它的招牌。',
    links: {
      hf: 'https://huggingface.co/Wan-AI/Wan2.2-T2V-A14B',
      github: 'https://github.com/Wan-Video/Wan2.2',
    },
  },
  {
    slug: 'wan2-2-i2v-a14b',
    title: 'Wan2.2 I2V A14B',
    org: '阿里巴巴通义万相',
    family: 'Wan',
    released: '2025-07-28',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'MoE DiT（图生视频）',
    params: '27B（激活 14B）',
    repo: 'Wan-AI/Wan2.2-I2V-A14B',
    summary: 'Wan2.2 的图生视频版本，延续 MoE 设计，在保持首帧一致的同时把运动幅度做上去。',
    links: {
      hf: 'https://huggingface.co/Wan-AI/Wan2.2-I2V-A14B',
      github: 'https://github.com/Wan-Video/Wan2.2',
    },
  },
  {
    slug: 'wan2-2-ti2v-5b',
    title: 'Wan2.2 TI2V 5B',
    org: '阿里巴巴通义万相',
    family: 'Wan',
    released: '2025-07-28',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'DiT（文生 / 图生统一，5B）',
    params: '5B',
    repo: 'Wan-AI/Wan2.2-TI2V-5B',
    vram: '单张消费级 24G 显卡可跑 720P',
    summary: 'Wan2.2 里最轻的一档，5B 权重在单张消费级显卡上跑 720P，把这一代的可用门槛压到最低。',
    links: {
      hf: 'https://huggingface.co/Wan-AI/Wan2.2-TI2V-5B',
      github: 'https://github.com/Wan-Video/Wan2.2',
    },
  },
  {
    slug: 'matrix-game-2-0',
    title: 'Matrix-Game 2.0',
    org: '昆仑万维 Skywork',
    family: 'Matrix-Game',
    released: '2025-08-12',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '流式交互世界模型 DiT',
    repo: 'Skywork/Matrix-Game-2.0',
    summary: 'Matrix-Game 的 2.0 版，把实时流式交互做到 25fps 级别，开源世界模型第一次逼近「可玩」体验。',
    links: {
      hf: 'https://huggingface.co/Skywork/Matrix-Game-2.0',
      github: 'https://github.com/SkyworkAI/Matrix-Game',
      paper: 'https://arxiv.org/abs/2508.13009',
    },
  },
  {
    slug: 'hunyuan-gamecraft',
    title: 'Hunyuan-GameCraft-1.0',
    org: '腾讯混元',
    family: 'Hunyuan',
    released: '2025-08-13',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'Tencent Hunyuan Community License',
    architecture: 'DiT（动作条件世界模型）',
    repo: 'tencent/Hunyuan-GameCraft-1.0',
    summary: '腾讯开源的游戏世界模型，用动作信号驱动可控游戏画面生成，面向「边玩边生成」的互动内容。',
    links: {
      hf: 'https://huggingface.co/tencent/Hunyuan-GameCraft-1.0',
      github: 'https://github.com/Tencent-Hunyuan/Hunyuan-GameCraft-1.0',
    },
  },
  {
    slug: 'wan2-2-s2v-14b',
    title: 'Wan2.2-S2V-14B',
    org: '阿里巴巴通义万相',
    family: 'Wan',
    released: '2025-08-26',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'DiT（音频驱动视频）',
    params: '16.3B',
    repo: 'Wan-AI/Wan2.2-S2V-14B',
    summary: '万相的语音驱动视频模型，音频加一张图就能生成分钟级的说话视频，长时序稳定性是重点。',
    links: {
      hf: 'https://huggingface.co/Wan-AI/Wan2.2-S2V-14B',
      github: 'https://github.com/Wan-Video/Wan2.2',
    },
  },
  {
    slug: 'hunyuanworld-voyager',
    title: 'HunyuanWorld-Voyager',
    org: '腾讯混元',
    family: 'Hunyuan',
    released: '2025-08-27',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'Tencent Hunyuan Community License',
    architecture: 'DiT（3D 世界模型）',
    repo: 'tencent/HunyuanWorld-Voyager',
    summary: '腾讯开源的世界模型，用「边走边生成」的方式做可探索的 3D 场景视频，面向游戏与仿真。',
    links: {
      hf: 'https://huggingface.co/tencent/HunyuanWorld-Voyager',
      github: 'https://github.com/Tencent-Hunyuan/HunyuanWorld-Voyager',
      paper: 'https://arxiv.org/abs/2508.17196',
    },
  },
  {
    slug: 'wan2-2-animate-14b',
    title: 'Wan2.2-Animate-14B',
    org: '阿里巴巴通义万相',
    family: 'Wan',
    released: '2025-09-19',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'DiT（角色动画 / 替换）',
    params: '17.3B',
    repo: 'Wan-AI/Wan2.2-Animate-14B',
    summary: '万相的角色动画模型，把参考视频里的动作迁移到任意角色并替换场景，是开源角色动画的分水岭。',
    links: {
      hf: 'https://huggingface.co/Wan-AI/Wan2.2-Animate-14B',
      github: 'https://github.com/Wan-Video/Wan2.2',
    },
  },
  {
    slug: 'lucy-edit-dev',
    title: 'Lucy Edit Dev',
    org: 'Decart',
    family: 'Lucy',
    released: '2025-09-16',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'Decart Lucy 自定义许可',
    architecture: 'DiT（指令式视频编辑）',
    params: '5.0B',
    repo: 'decart-ai/Lucy-Edit-Dev',
    summary: 'Decart 开源的实时视频编辑模型，换衣服、改场景这类指令在单卡上就能做到接近实时。',
    links: {
      hf: 'https://huggingface.co/decart-ai/Lucy-Edit-Dev',
    },
  },
  {
    slug: 'longcat-video',
    title: 'LongCat-Video',
    org: '美团 LongCat 团队',
    family: 'LongCat',
    released: '2025-10-25',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: 'DiT（文生 / 图生 / 续写统一）',
    params: '13.6B',
    repo: 'meituan-longcat/LongCat-Video',
    summary: '美团开源的 13.6B 视频模型，一套权重覆盖文生、图生与视频续写，MIT 许可可直接商用。',
    links: {
      hf: 'https://huggingface.co/meituan-longcat/LongCat-Video',
      github: 'https://github.com/meituan-longcat/LongCat-Video',
      paper: 'https://arxiv.org/abs/2510.22200',
    },
  },
  {
    slug: 'sana-video-2b',
    title: 'SANA-Video 2B',
    org: 'NVIDIA',
    family: 'SANA',
    released: '2025-10-27',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '线性注意力 DiT（块线性注意力）',
    params: '2B',
    repo: 'Efficient-Large-Model/SANA-Video_2B_480p',
    summary: 'NVIDIA 把 SANA 的高效路线搬到视频上，2B 权重就能出 720P 视频，对消费级显卡很友好。',
    links: {
      hf: 'https://huggingface.co/Efficient-Large-Model/SANA-Video_2B_480p',
      github: 'https://github.com/NVlabs/Sana',
      paper: 'https://arxiv.org/abs/2509.24695',
    },
  },
  {
    slug: 'kandinsky-5-0-i2v-lite',
    title: 'Kandinsky 5.0 I2V Lite',
    org: 'Sber AI（Kandinsky Lab）',
    family: 'Kandinsky',
    released: '2025-11-15',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '潜在扩散 Transformer（Lite，图生视频）',
    params: '2B',
    repo: 'kandinskylab/Kandinsky-5.0-I2V-Lite-5s',
    summary: 'Sber 的轻量图生视频权重，MIT 许可，俄语与英语提示都能用，是俄语区开源视频方案的代表。',
    links: {
      hf: 'https://huggingface.co/kandinskylab/Kandinsky-5.0-I2V-Lite-5s',
      github: 'https://github.com/ai-forever/Kandinsky-5',
      paper: 'https://arxiv.org/abs/2511.14993',
    },
  },
  {
    slug: 'hunyuanvideo-1-5',
    title: 'HunyuanVideo 1.5',
    org: '腾讯混元',
    family: 'Hunyuan',
    released: '2025-11-20',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'Tencent Hunyuan Community License',
    architecture: 'DiT（8.3B 主干 + 高压缩 VAE）',
    params: '8.3B',
    repo: 'tencent/HunyuanVideo-1.5',
    summary: '混元视频的 1.5 版，把参数量压到 8.3B 却把画质与运动做上去，单卡可跑，是 2025 年底最强的一档开源视频模型。',
    links: {
      hf: 'https://huggingface.co/tencent/HunyuanVideo-1.5',
      github: 'https://github.com/Tencent-Hunyuan/HunyuanVideo-1.5',
      paper: 'https://arxiv.org/abs/2511.18870',
    },
  },
  {
    slug: 'hy-worldplay',
    title: 'HY-WorldPlay',
    org: '腾讯混元',
    family: 'Hunyuan',
    released: '2025-12-12',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'Tencent Hunyuan Community License',
    architecture: 'DiT（可交互世界模型）',
    repo: 'tencent/HY-WorldPlay',
    summary: '腾讯混元的世界模型新作，把动作控制与场景一致性结合，做可交互的连续世界探索。',
    links: {
      hf: 'https://huggingface.co/tencent/HY-WorldPlay',
      github: 'https://github.com/Tencent-Hunyuan/HY-WorldPlay',
    },
  },
  {
    slug: 'longcat-video-avatar',
    title: 'LongCat-Video-Avatar',
    org: '美团 LongCat 团队',
    family: 'LongCat',
    released: '2025-12-16',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: 'DiT（音频驱动数字人）',
    repo: 'meituan-longcat/LongCat-Video-Avatar',
    summary: '美团开源的长视频数字人模型，支持单人、多人对话与长视频续写，MIT 许可下可直接商用。',
    links: {
      hf: 'https://huggingface.co/meituan-longcat/LongCat-Video-Avatar',
      github: 'https://github.com/meituan-longcat/LongCat-Video',
    },
  },

{
    slug: 'humo',
    title: 'HuMo',
    org: '字节跳动 ByteDance',
    family: 'HuMo',
    released: '2025-09-10',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'DiT（文本 + 参考图 + 音频三条件，17B）',
    params: '17B',
    repo: 'bytedance-research/HuMo',
    summary: '字节的人本视频模型，同时吃文本、参考图和音频，音画同步与主体身份保持是它的重点。',
    links: {
      hf: 'https://huggingface.co/bytedance-research/HuMo',
      paper: 'https://arxiv.org/abs/2509.08519',
    },
  },
  {
    slug: 'lynx',
    title: 'Lynx',
    org: '字节跳动 ByteDance',
    family: 'Lynx',
    released: '2025-09-26',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'DiT + ID-adapter / Ref-adapter（基于 Wan2.1-T2V-14B）',
    params: '14B',
    repo: 'ByteDance/lynx',
    summary: '字节从单张人像生成个性化视频的方案，用轻量身份适配器守住人脸一致性，另配 24fps 的 Lite 版本。',
    links: {
      hf: 'https://huggingface.co/ByteDance/lynx',
      github: 'https://github.com/bytedance/lynx',
      paper: 'https://arxiv.org/abs/2509.15496',
    },
  },
  {
    slug: 'kandinsky-5-0-t2v-lite',
    title: 'Kandinsky 5.0 T2V Lite',
    org: 'Sber AI（Kandinsky Lab）',
    family: 'Kandinsky',
    released: '2025-09-29',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '潜在扩散 Transformer + 3D VAE（Lite）',
    params: '2B',
    repo: 'kandinskylab/Kandinsky-5.0-T2V-Lite-sft-5s',
    summary: '只有 2B 的轻量文生视频模型，预训练、SFT、CFG 蒸馏与少步蒸馏权重一次放齐。',
    links: {
      hf: 'https://huggingface.co/kandinskylab/Kandinsky-5.0-T2V-Lite-sft-5s',
      github: 'https://github.com/kandinskylab/kandinsky-5',
      paper: 'https://arxiv.org/abs/2511.14993',
    },
  },
  {
    slug: 'ovi',
    title: 'Ovi',
    org: 'Character AI',
    family: 'Ovi',
    released: '2025-09-30',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '双塔 DiT（视频 5B + 音频 5B + 1B 融合）',
    params: '11.7B',
    repo: 'chetwinlow1/Ovi',
    summary: '把画面与声音放进同一次生成过程的双塔模型，音效、音乐与口型天然同步，不用再事后对齐。',
    links: {
      hf: 'https://huggingface.co/chetwinlow1/Ovi',
      github: 'https://github.com/character-ai/Ovi',
      paper: 'https://arxiv.org/abs/2510.01284',
    },
  },
  {
    slug: 'cosmos-predict2-5',
    title: 'Cosmos-Predict2.5',
    org: 'NVIDIA',
    family: 'Cosmos',
    released: '2025-10-06',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'NVIDIA Open Model License',
    architecture: '流匹配 DiT（2B / 14B）',
    params: '2B / 14B',
    repo: 'nvidia/Cosmos-Predict2.5-2B',
    summary: '统一 Text2World / Image2World / Video2World 的世界基础模型，为机器人与自动驾驶预测物理合理的未来画面。',
    links: {
      hf: 'https://huggingface.co/nvidia/Cosmos-Predict2.5-2B',
      github: 'https://github.com/nvidia-cosmos/cosmos-predict2.5',
      paper: 'https://arxiv.org/abs/2511.00062',
    },
  },
  {
    slug: 'video-as-prompt',
    title: 'Video-As-Prompt',
    org: '字节跳动 ByteDance',
    family: 'VAP',
    released: '2025-10-22',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'DiT（Wan2.1-I2V-14B 与 CogVideoX-5B 两个基座）',
    params: '14B',
    repo: 'ByteDance/Video-As-Prompt-Wan2.1-14B',
    summary: '把一段参考视频当成「提示词」来做统一语义控制，不用按任务重训就能迁移运动、风格与主体语义。',
    links: {
      hf: 'https://huggingface.co/ByteDance/Video-As-Prompt-Wan2.1-14B',
      paper: 'https://arxiv.org/abs/2510.20888',
    },
  },
  {
    slug: 'kaleido-14b-s2v',
    title: 'Kaleido-14B-S2V',
    org: '智谱 AI',
    family: 'Kaleido',
    released: '2025-10-28',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: 'DiT（基于 Wan2.1-T2V-14B 的多主体参考）',
    params: '14B',
    repo: 'zai-org/Kaleido-14B-S2V',
    summary: '智谱的多主体参考图生视频框架，多张参考图条件下同时保持主体一致并把背景解耦开。',
    links: {
      hf: 'https://huggingface.co/zai-org/Kaleido-14B-S2V',
      paper: 'https://arxiv.org/abs/2510.18573',
    },
  },
  {
    slug: 'bindweave',
    title: 'BindWeave',
    org: '字节跳动 ByteDance',
    family: 'BindWeave',
    released: '2025-11-04',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'DiT + 跨模态融合（基于 Wan 系开放基座）',
    params: '14B',
    repo: 'ByteDance/BindWeave',
    summary: '让多个主体在复杂空间关系与时间逻辑下保持一致，明显缓解多主体视频里的语义漂移。',
    links: {
      hf: 'https://huggingface.co/ByteDance/BindWeave',
      paper: 'https://arxiv.org/abs/2510.00438',
    },
  },
  {
    slug: 'kandinsky-5-0-t2v-pro',
    title: 'Kandinsky 5.0 T2V Pro',
    org: 'Sber AI（Kandinsky Lab）',
    family: 'Kandinsky',
    released: '2025-11-20',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '潜在扩散 Transformer + 3D VAE（19B 旗舰）',
    params: '19B',
    repo: 'kandinskylab/Kandinsky-5.0-T2V-Pro-sft-5s',
    summary: 'Kandinsky 5.0 的 19B 旗舰版本，文生视频与图生视频同时开放，曾在 LMArena 开源文生视频榜登顶。',
    links: {
      hf: 'https://huggingface.co/kandinskylab/Kandinsky-5.0-T2V-Pro-sft-5s',
      github: 'https://github.com/kandinskylab/kandinsky-5',
      paper: 'https://arxiv.org/abs/2511.14993',
    },
  },
  {
    slug: 'scail-preview',
    title: 'SCAIL-Preview',
    org: '智谱 AI',
    family: 'SCAIL',
    released: '2025-12-08',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: 'DiT + 3D 一致姿态表示（基于 Wan-I2V）',
    params: '14B',
    repo: 'zai-org/SCAIL-Preview',
    summary: '智谱的角色动画预览版，用 3D 一致姿态做上下文学习，大幅动作与风格化角色下结构都还稳。',
    links: {
      hf: 'https://huggingface.co/zai-org/SCAIL-Preview',
      github: 'https://github.com/zai-org/SCAIL',
      paper: 'https://arxiv.org/abs/2512.05905',
    },
  },
  {
    slug: 'longsana',
    title: 'LongSANA',
    org: 'NVIDIA',
    family: 'SANA',
    released: '2025-12-09',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '线性注意力 DiT + 长上下文扩展',
    params: '2B',
    repo: 'Efficient-Large-Model/SANA-Video_2B_480p_LongLive',
    summary: '把 SANA-Video 与 LongLive 的长上下文扩展拼起来，单卡能做到 27FPS 生成分钟级连续视频。',
    links: {
      hf: 'https://huggingface.co/Efficient-Large-Model/SANA-Video_2B_480p_LongLive',
      github: 'https://github.com/NVlabs/Sana',
    },
  },
  {
    slug: 'longvie-2',
    title: 'LongVie 2',
    org: '上海人工智能实验室 Vchitect',
    family: 'LongVie',
    released: '2025-12-14',
    output: 'video',
    tags: ['自回归'],
    commercial: '不可商用',
    license: '未声明许可',
    architecture: '自回归 DiT + 深度 / 点图控制（基于 Wan2.1-I2V-14B）',
    params: '14B',
    repo: 'Vchitect/LongVie2',
    summary: '上海 AI Lab 的超长视频世界模型，靠深度与点图控制信号在分钟尺度上维持几何与时序一致。',
    links: {
      hf: 'https://huggingface.co/Vchitect/LongVie2',
      github: 'https://github.com/Vchitect/LongVie',
      paper: 'https://arxiv.org/abs/2512.13604',
    },
  },

  /* ============================ 生视频 · 2026 ============================ */
  {
    slug: 'ltx-2',
    title: 'LTX-2',
    org: 'Lightricks',
    family: 'LTX',
    released: '2026-01-05',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'LTX-2 Community License Agreement',
    architecture: '音视频联合 DiT（19B）',
    params: '18.9B',
    repo: 'Lightricks/LTX-2',
    summary: 'Lightricks 首个开源音视频联合生成基础模型，一次生成自带同步音频的视频，是 2026 年开源视频模型的序章。',
    links: {
      hf: 'https://huggingface.co/Lightricks/LTX-2',
      github: 'https://github.com/Lightricks/LTX-2',
      paper: 'https://arxiv.org/abs/2601.03233',
    },
  },
  {
    slug: 'skyreels-v3',
    title: 'SkyReels V3',
    org: '昆仑万维 Skywork',
    family: 'SkyReels',
    released: '2026-01-29',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'Skywork 模型社区许可协议',
    architecture: '统一多模态 in-context 视频 DiT',
    params: '19B（A2V）/ 14B（R2V、V2V）',
    repo: 'Skywork/SkyReels-V3-A2V-19B',
    summary: '昆仑万维的多模态上下文视频模型，一个框架同时覆盖参考图生视频、视频续写与音频驱动数字人。',
    links: {
      hf: 'https://huggingface.co/Skywork/SkyReels-V3-A2V-19B',
      github: 'https://github.com/SkyworkAI/SkyReels-V3',
      paper: 'https://arxiv.org/abs/2601.17323',
    },
  },
  {
    slug: 'lingbot-world',
    title: 'LingBot-World',
    org: '蚂蚁灵波科技',
    family: 'LingBot',
    released: '2026-01-29',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '实时交互世界模型（基于 Wan2.2 主干）',
    params: '14B',
    repo: 'robbyant/lingbot-world-base-cam',
    summary: '蚂蚁灵波首个开源实时交互世界模型，可稳定生成长达分钟级的高保真视频，是国产开源世界模型的代表。',
    links: {
      hf: 'https://huggingface.co/robbyant/lingbot-world-base-cam',
      github: 'https://github.com/robbyant/lingbot-world',
      paper: 'https://arxiv.org/abs/2601.20540',
    },
  },
  {
    slug: 'ltx-2-3',
    title: 'LTX-2.3',
    org: 'Lightricks',
    family: 'LTX',
    released: '2026-03-05',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'LTX-2 Community License Agreement',
    architecture: '多模态 DiT（20.9B）',
    params: '20.9B',
    repo: 'Lightricks/LTX-2.3',
    summary: 'Lightricks 的 20.9B 多模态视频模型，主打消费级显卡本地推理与 4K 输出，把开源视频生成推向商用可用。',
    links: {
      hf: 'https://huggingface.co/Lightricks/LTX-2.3',
      github: 'https://github.com/Lightricks/LTX-2',
      paper: 'https://arxiv.org/abs/2601.03233',
    },
  },
  {
    slug: 'davinci-magihuman',
    title: 'daVinci-MagiHuman',
    org: '上海交通大学 SII-GAIR / Sand.ai',
    family: 'MAGI',
    released: '2026-03-21',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '单流音视频生成架构',
    repo: 'GAIR/daVinci-MagiHuman',
    summary: 'SII-GAIR 与 Sand.ai 合作的开源音视频基础模型，用单流架构换速度，说话人视频一次成片。',
    links: {
      hf: 'https://huggingface.co/GAIR/daVinci-MagiHuman',
      github: 'https://github.com/GAIR-NLP/daVinci-MagiHuman',
      paper: 'https://arxiv.org/abs/2603.21986',
    },
  },
  {
    slug: 'matrix-game-3-0',
    title: 'Matrix-Game 3.0',
    org: '昆仑万维 Skywork',
    family: 'Matrix-Game',
    released: '2026-03-27',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '流式交互世界模型 DiT',
    repo: 'Skywork/Matrix-Game-3.0',
    summary: 'Matrix-Game 的 3.0 版，交互世界模型的稳定性与长时一致性继续提升，许可也换成了更干净的 Apache-2.0。',
    links: {
      hf: 'https://huggingface.co/Skywork/Matrix-Game-3.0',
      github: 'https://github.com/SkyworkAI/Matrix-Game',
    },
  },
  {
    slug: 'void-model',
    title: 'VOID',
    org: 'Netflix',
    family: 'VOID',
    released: '2026-03-30',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '视频扩散（对象与交互擦除）',
    repo: 'netflix/void-model',
    summary: 'Netflix 开源的视频物体擦除模型，连物体删掉后引发的物理连锁变化一起重绘，是目前最会「擦」的开源视频模型。',
    links: {
      hf: 'https://huggingface.co/netflix/void-model',
      github: 'https://github.com/netflix/void-model',
      paper: 'https://arxiv.org/abs/2604.02296',
    },
  },
  {
    slug: 'hy-omniweaving',
    title: 'HY-OmniWeaving',
    org: '腾讯混元',
    family: 'Hunyuan',
    released: '2026-04-03',
    output: 'video',
    tags: ['MMDiT'],
    commercial: '有条件可商用',
    license: 'Tencent Hunyuan Community License',
    architecture: 'MLLM + MMDiT + VAE 统一视频生成框架',
    params: '8.3B',
    repo: 'tencent/HY-OmniWeaving',
    summary: '腾讯混元把 MLLM 接进视频生成，支持多图组合、参考图与视频编辑等自由形态输入，还带了一套智能视频生成基准。',
    links: {
      hf: 'https://huggingface.co/tencent/HY-OmniWeaving',
      github: 'https://github.com/Tencent-Hunyuan/OmniWeaving',
      paper: 'https://arxiv.org/abs/2603.24458',
    },
  },
  {
    slug: 'longlive-2-0',
    title: 'LongLive-2.0',
    org: 'NVIDIA',
    family: 'LongLive',
    released: '2026-05-17',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'NVIDIA Open Model License',
    architecture: '长视频 DiT（基于 Wan2.2 主干，5B）',
    params: '5B',
    repo: 'Efficient-Large-Model/LongLive-2.0-5B',
    summary: 'NVIDIA 的多镜头长视频生成模型，在 Wan2.2 基础上解决长时序一致性，面向长叙事视频。',
    links: {
      hf: 'https://huggingface.co/Efficient-Large-Model/LongLive-2.0-5B',
      paper: 'https://arxiv.org/abs/2605.18739',
    },
  },
  {
    slug: 'sana-wm',
    title: 'SANA-WM',
    org: 'NVIDIA',
    family: 'SANA',
    released: '2026-05-18',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '混合线性注意力 DiT（2.6B）',
    params: '2.6B',
    repo: 'Efficient-Large-Model/SANA-WM_bidirectional',
    summary: 'NVIDIA 的分钟级世界模型，单卡就能生成 60 秒 720p 视频并支持 6 自由度相机轨迹控制。',
    links: {
      hf: 'https://huggingface.co/Efficient-Large-Model/SANA-WM_bidirectional',
      paper: 'https://arxiv.org/abs/2605.15178',
    },
  },
  {
    slug: 'cosmos3-super-image2video',
    title: 'Cosmos3-Super-Image2Video',
    org: 'NVIDIA',
    family: 'Cosmos',
    released: '2026-05-21',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'NVIDIA Open Model License',
    architecture: '全模态世界模型（64.6B）',
    params: '64.6B',
    repo: 'nvidia/Cosmos3-Super-Image2Video',
    summary: 'Cosmos 3 世界模型平台的图生视频入口，64.6B 参数面向机器人、自动驾驶这类物理 AI 场景。',
    links: {
      hf: 'https://huggingface.co/nvidia/Cosmos3-Super-Image2Video',
      github: 'https://github.com/nvidia/cosmos',
    },
  },
  {
    slug: 'longcat-video-avatar-1-5',
    title: 'LongCat-Video-Avatar 1.5',
    org: '美团 LongCat 团队',
    family: 'LongCat',
    released: '2026-05-25',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '音频驱动数字人 DiT（DMD 蒸馏 8 步）',
    params: '13.6B',
    repo: 'meituan-longcat/LongCat-Video-Avatar-1.5',
    summary: '美团开源的商用级音频驱动数字人视频模型，支持单人多人对话与长视频续写，MIT 许可可直接商用。',
    links: {
      hf: 'https://huggingface.co/meituan-longcat/LongCat-Video-Avatar-1.5',
      github: 'https://github.com/meituan-longcat/LongCat-Video',
    },
  },
  {
    slug: 'nava',
    title: 'NAVA',
    org: '百度 ERNIE 团队',
    family: 'NAVA',
    released: '2026-05-29',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '原生音视频对齐 DiT（基于 Wan2.2 TI2V-5B）',
    params: '6.3B',
    repo: 'baidu/NAVA',
    summary: '百度 6.3B 的音视频生成模型，把口型、音效与画面同步做进同一套权重，音画对齐是它的核心卖点。',
    links: {
      hf: 'https://huggingface.co/baidu/NAVA',
      github: 'https://github.com/ernie-research/NAVA',
      paper: 'https://arxiv.org/abs/2605.30073',
    },
  },
  {
    slug: 'bernini-r',
    title: 'Bernini-R',
    org: '字节跳动',
    family: 'Bernini',
    released: '2026-06-01',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '视频扩散 + 潜在语义规划',
    repo: 'ByteDance/Bernini-R',
    summary: '字节的视频生成渲染器，先用语义规划把「要发生什么」排好再交给扩散渲染，复杂多主体场景更稳。',
    links: {
      hf: 'https://huggingface.co/ByteDance/Bernini-R',
      paper: 'https://arxiv.org/abs/2605.22344',
    },
  },
  {
    slug: 'joyai-echo',
    title: 'JoyAI-Echo 1.5',
    org: '京东 jd-opensource',
    family: 'JoyAI',
    released: '2026-06-02',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'JoyAI Echo 自定义许可',
    architecture: '长时音视频生成 DiT（8 步 DMD）',
    params: '19.0B',
    repo: 'jdopensource/JoyAI-Echo',
    summary: '京东的长时音视频生成模型，面向连续故事与可交互世界，一次能续出带同步音频的长视频。',
    links: {
      hf: 'https://huggingface.co/jdopensource/JoyAI-Echo',
      github: 'https://github.com/jd-opensource/JoyAI-Echo',
      paper: 'https://arxiv.org/abs/2608.23383',
    },
  },
  {
    slug: 'scail-2',
    title: 'SCAIL-2',
    org: '智谱 AI',
    family: 'SCAIL',
    released: '2026-06-09',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '端到端 in-context 角色动画 DiT（Wan VAE + umT5）',
    repo: 'zai-org/SCAIL-2',
    summary: '智谱开源的角色动画模型，用端到端驱动替代骨骼等中间表示，换了角色或换成动物也能驱动。',
    links: {
      hf: 'https://huggingface.co/zai-org/SCAIL-2',
      github: 'https://github.com/zai-org/SCAIL-2',
      paper: 'https://arxiv.org/abs/2606.10804',
    },
  },
  {
    slug: 'lingbot-video',
    title: 'LingBot-Video',
    org: '蚂蚁灵波科技',
    family: 'LingBot',
    released: '2026-07-09',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: 'MoE DiT（30B 总参 / 3B 激活）',
    params: '30.1B（激活 3B）',
    repo: 'robbyant/lingbot-video-moe-30b-a3b',
    summary: '蚂蚁灵波面向具身智能的 MoE 视频模型，用 7 万小时具身数据训练，30B 总参只激活 3B，推理效率提升约三倍。',
    links: {
      hf: 'https://huggingface.co/robbyant/lingbot-video-moe-30b-a3b',
      github: 'https://github.com/Robbyant/lingbot-video',
    },
  },
  {
    slug: 'lingbot-world-2-0',
    title: 'LingBot-World 2.0',
    org: '蚂蚁灵波科技',
    family: 'LingBot',
    released: '2026-07-09',
    output: 'video',
    tags: ['DiT'],
    commercial: '不可商用',
    license: 'CC-BY-NC-SA-4.0',
    architecture: '因果预训练实时交互世界模型（MoBA 混合注意力）',
    params: '14B',
    repo: 'robbyant/lingbot-world-v2-14b-causal-fast',
    summary: '蚂蚁灵波的小时级实时交互世界模型，720p/60fps 稳定输出，并首次把 Agent 机制引入世界模型。',
    links: {
      hf: 'https://huggingface.co/robbyant/lingbot-world-v2-14b-causal-fast',
      github: 'https://github.com/robbyant/lingbot-world-v2',
      paper: 'https://arxiv.org/abs/2607.07534',
    },
  },
  {
    slug: 'abot-world',
    title: 'ABot-World-0.5B',
    org: '高德 amap-cvlab',
    family: 'ABot-World',
    released: '2026-07-09',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '交互式世界模型 DiT（文档称 0.5B 档）',
    params: '5.3B',
    repo: 'acvlab/ABot-World-0-5B-LF',
    summary: '面向单张桌面显卡的无限交互世界模型，把「实时可玩」的世界生成压到消费级硬件上。',
    links: {
      hf: 'https://huggingface.co/acvlab/ABot-World-0-5B-LF',
      github: 'https://github.com/amap-cvlab/ABot-World',
    },
  },
  {
    slug: 'wan-dancer',
    title: 'Wan-Dancer',
    org: '阿里巴巴通义万相',
    family: 'Wan',
    released: '2026-07-13',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '分层 DiT（全局关键帧规划 + 局部时序精修）',
    params: '14B',
    repo: 'Wan-AI/Wan-Dancer-14B',
    summary: '阿里万相的分钟级音乐驱动舞蹈视频模型，用全局关键帧加局部精修实现长程动作连贯。',
    links: {
      hf: 'https://huggingface.co/Wan-AI/Wan-Dancer-14B',
      github: 'https://github.com/Wan-Video/Wan-Dancer',
      paper: 'https://arxiv.org/abs/2607.09581',
    },
  },
  {
    slug: 'kandinsky-wm-1-0',
    title: 'Kandinsky-WM 1.0',
    org: 'Sber AI（Kandinsky Lab）',
    family: 'Kandinsky',
    released: '2026-07-13',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'MIT',
    architecture: '世界模型 DiT（图生视频 5 秒）',
    params: '2B',
    repo: 'kandinskylab/Kandinsky-WM-1.0-I2V-5s-PH',
    summary: 'Sber 的世界模型新作，2B 权重以 MIT 开放，主打物理一致的短视频世界推演。',
    links: {
      hf: 'https://huggingface.co/kandinskylab/Kandinsky-WM-1.0-I2V-5s-PH',
      github: 'https://github.com/ai-forever/Kandinsky-5',
    },
  },
  {
    slug: 'minimax-h3',
    title: 'MiniMax H3',
    org: 'MiniMax',
    family: 'MiniMax H3',
    released: '2026-08-03',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'MiniMax H3 Community License Agreement',
    architecture: '33B 稠密单流 Omni-Transformer（Qwen3-VL-32B 编码器）',
    params: '33.1B',
    repo: 'MiniMaxAI/MiniMax-H3',
    summary: 'MiniMax 开源的全模态音视频生成模型，最高 2K、15 秒、原生立体声，是国产开源视频模型的性能标杆。',
    links: {
      hf: 'https://huggingface.co/MiniMaxAI/MiniMax-H3',
      github: 'https://github.com/MiniMax-AI/MiniMax-H3',
    },
  },
  {
    slug: 'magi-2-preview',
    title: 'MAGI-2 Preview',
    org: 'Sand.ai',
    family: 'MAGI',
    released: '2026-08-03',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '超细粒度 MoE 统一音视频 DiT（114B 总参 / 6B 激活）',
    params: '114B（激活 6B）',
    repo: 'sand-ai/MAGI-2-preview',
    summary: 'Sand.ai 开源的千亿级 MoE 视频模型，114B 总参数单次只激活 6B，把超大模型的推理成本压了下来。',
    links: {
      hf: 'https://huggingface.co/sand-ai/MAGI-2-preview',
      github: 'https://github.com/SandAI-org/MAGI-2-preview',
    },
  },
  {
    slug: 'joyai-video-edit',
    title: 'JoyAI-Video-Edit',
    org: '京东 jd-opensource',
    family: 'JoyAI',
    released: '2026-08-04',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '指令式视频编辑 DiT',
    repo: 'jdopensource/JoyAI-Video-Edit',
    summary: '京东的指令式视频编辑模型，用自然语言改视频内容并保持时序一致，Apache-2.0 可商用。',
    links: {
      hf: 'https://huggingface.co/jdopensource/JoyAI-Video-Edit',
      github: 'https://github.com/jd-opensource/JoyAI-Video-Edit',
    },
  },
  {
    slug: 'wan-animate-2',
    title: 'Wan-Animate-2',
    org: '阿里巴巴通义万相',
    family: 'Wan',
    released: '2026-08-07',
    output: 'video',
    tags: ['DiT'],
    commercial: '可商用',
    license: 'Apache-2.0',
    architecture: '端到端角色动画 DiT（直接消费驱动视频）',
    params: '14B',
    repo: 'Wan-AI/Wan2.2-Animate-2-14B',
    summary: '万相的角色动画第二代，取消中间动作提取器实现端到端驱动，还能用文本解耦出想要的镜头视角。',
    links: {
      hf: 'https://huggingface.co/Wan-AI/Wan2.2-Animate-2-14B',
      github: 'https://github.com/Wan-Video/Wan-Animate-2',
      paper: 'https://arxiv.org/abs/2608.06009',
    },
  },
  {
    slug: 'ltx-2-5',
    title: 'LTX-2.5',
    org: 'Lightricks',
    family: 'LTX',
    released: '2026-08-11',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'LTX-2 Community License Agreement',
    architecture: '音视频联合 DiT（DiffVAE + Gemma 4 编码器）',
    params: '22B',
    repo: 'Lightricks/LTX-2.5',
    summary: 'Lightricks 最新的开源音视频世界模型，原生多镜头一次成片并支持 4K HDR，是当前开源视频模型的头部选手。',
    links: {
      hf: 'https://huggingface.co/Lightricks/LTX-2.5',
      github: 'https://github.com/Lightricks/LTX-2',
      paper: 'https://arxiv.org/abs/2601.03233',
    },
  },
  {
    slug: '4danyone',
    title: '4DAnyone',
    org: '蚂蚁集团 AntResearch',
    family: '4DAnyone',
    released: '2026-08-17',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: '资产级许可（见仓库 LICENSE.md）',
    architecture: '视频扩散 + 人体先验（基于 Wan2.2 主干）',
    repo: 'AntResearch/4DAnyone',
    summary: '蚂蚁开源的 4D 人物重建模型，用一段普通手机视频生成多视角视频，接上 4DGS 就能重建可动的三维人物。',
    links: {
      hf: 'https://huggingface.co/AntResearch/4DAnyone',
      github: 'https://github.com/ant-research/4DAnyone',
      paper: 'https://arxiv.org/abs/2608.20335',
    },
  },
  {
    slug: 'viggle-animate',
    title: 'Viggle-Animate',
    org: 'Viggle',
    family: 'Viggle',
    released: '2026-08-31',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'Viggle 自定义许可（基于 MiniMax H3）',
    architecture: '角色替换 DiT（基于 MiniMax H3）',
    params: '33.1B',
    repo: 'Viggle/Viggle-Animate',
    summary: 'Viggle 开源的角色替换模型，只要重画一帧就能把整段视频里的人物换成新角色，身份与时序都保得住。',
    links: {
      hf: 'https://huggingface.co/Viggle/Viggle-Animate',
    },
  },
  {
    slug: 'lingbot-world-2-0-small',
    title: 'LingBot-World 2.0 Small',
    org: '蚂蚁灵波科技',
    family: 'LingBot',
    released: '2026-09-04',
    output: 'video',
    tags: ['DiT'],
    commercial: '不可商用',
    license: 'CC-BY-NC-SA-4.0',
    architecture: '因果实时交互世界模型轻量版',
    params: '1.3B',
    repo: 'robbyant/lingbot-world-v2-1.3b-causal-fast',
    summary: '蚂蚁灵波为消费级单卡设计的 1.3B 实时世界模型，让个人开发者也能在本地跑起实时交互视频生成。',
    links: {
      hf: 'https://huggingface.co/robbyant/lingbot-world-v2-1.3b-causal-fast',
      github: 'https://github.com/robbyant/lingbot-world-v2',
      paper: 'https://arxiv.org/abs/2607.07534',
    },
  },
  {
    slug: 'xgen-jing',
    title: 'XGEN-JING',
    org: 'XGEN Labs',
    family: 'XGEN',
    released: '2026-09-16',
    output: 'video',
    tags: ['DiT'],
    commercial: '有条件可商用',
    license: 'XGEN 自定义许可',
    architecture: '第一人称交互体验模型',
    repo: 'XGENlabs/XGEN-JING',
    summary: 'XGEN 实验室的第一人称交互体验模型，用输入信号实时驱动视角与画面，面向沉浸式内容与仿真。',
    links: {
      hf: 'https://huggingface.co/XGENlabs/XGEN-JING',
      github: 'https://github.com/XGEN-Labs/XGEN-JING',
    },
  },
];