/**
 * 收录清单（人工定稿）：2025-01 以来大厂 / 机构**自研**的开放权重 LLM。
 * 只含机构自己预训练/后训练的模型；社区微调、蒸馏、剪枝、换皮以及第三方对大厂模型的改造一律不收。
 *
 * 字段说明：
 *   repo      HuggingFace 仓库 ID（用于生成 hf 链接，并用 createdAt 交叉核验 released）
 *   released  以官方公告日为准；未注明的默认取 HF 仓库创建日（权重公开下载日）
 *   context / paramsExtra / vram  人工核定，HF config 不保证准确
 *   commercial 依据许可条款核定：可商用 / 有条件可商用 / 不可商用
 */
export const models = [
  // ---------------------------------------------------------------- DeepSeek
  {
    slug: 'deepseek-prover-v2',
    title: 'DeepSeek-Prover-V2',
    org: 'DeepSeek 深度求索',
    family: 'DeepSeek',
    repo: 'deepseek-ai/DeepSeek-Prover-V2-671B',
    released: '2025-04-30',
    summary: '把 685B 基座专门压到 Lean 4 形式化证明上的数学证明模型，定理证明通过率刷新开源记录。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 37B',
    context: '128K',
    vram: '全量需 8 卡 H200；4bit 量化约 350G 显存',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'deepseek-v3-2-exp',
    title: 'DeepSeek-V3.2-Exp',
    org: 'DeepSeek 深度求索',
    family: 'DeepSeek',
    repo: 'deepseek-ai/DeepSeek-V3.2-Exp',
    released: '2025-09-29',
    summary: '第一次把 DeepSeek Sparse Attention 放出来的实验版，长文本推理成本明显下降而效果几乎不掉。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 37B',
    context: '160K',
    vram: '全量需 8 卡 H200 级别',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'deepseek-ocr',
    title: 'DeepSeek-OCR',
    org: 'DeepSeek 深度求索',
    family: 'DeepSeek',
    repo: 'deepseek-ai/DeepSeek-OCR',
    released: '2025-10-17',
    summary: '用「视觉 token 压缩」读文档的开源 OCR 模型，把长文档塞进极少 token，单卡就能跑。',
    tags: ['Dense', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: null,
    vram: '单张 40G 卡可跑',
    modalities: ['text', 'image'],
    deploys: ['vllm'],
  },
  {
    slug: 'deepseek-math-v2',
    title: 'DeepSeek-Math-V2',
    org: 'DeepSeek 深度求索',
    family: 'DeepSeek',
    repo: 'deepseek-ai/DeepSeek-Math-V2',
    released: '2025-11-27',
    summary: '把「自我验证」训练进模型里的数学推理模型，开源模型里少见的 IMO 级证明能力。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'deepseek-v4-flash-0731',
    title: 'DeepSeek-V4-Flash-0731',
    org: 'DeepSeek 深度求索',
    family: 'DeepSeek',
    repo: 'deepseek-ai/DeepSeek-V4-Flash-0731',
    released: '2026-07-31',
    summary: 'V4-Flash 的 7 月更新版，把 agent 与代码能力又推一档，仍是百万上下文里最便宜的开源选择。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 13B',
    context: '1M',
    vram: '全量约 570G 显存；FP8 需 8 卡 H200',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'deepseek-v4-1-flash',
    title: 'DeepSeek-V4.1-Flash',
    org: 'DeepSeek 深度求索',
    family: 'DeepSeek',
    repo: 'deepseek-ai/DeepSeek-V4.1-Flash',
    released: '2026-09-10',
    summary: 'V4.1 代的 Flash 版本，长程任务稳定性与工具调用明显加强，仍是 MIT 许可。',
    tags: ['MoE', '可识别图像'],
    commercial: '可商用',
    paramsExtra: '激活 13B',
    context: '1M',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },

  // ------------------------------------------------------------------- Qwen
  {
    slug: 'qwen2-5-vl-72b',
    title: 'Qwen2.5-VL-72B',
    org: '阿里通义千问',
    family: 'Qwen',
    repo: 'Qwen/Qwen2.5-VL-72B-Instruct',
    released: '2025-01-27',
    summary: 'Qwen2.5-VL 最大的开源尺寸，能读长视频与文档里的表格，是 2025 年初最强的开源视觉语言模型。',
    tags: ['Dense', '可识别图像'],
    commercial: '有条件可商用',
    paramsExtra: null,
    context: '128K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'qwq-32b',
    title: 'QwQ-32B',
    org: '阿里通义千问',
    family: 'Qwen',
    repo: 'Qwen/QwQ-32B',
    released: '2025-03-06',
    summary: '32B 稠密模型靠强化学习追平 671B 级推理模型，消费级显卡也能跑的开源推理选择。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    vram: '4bit 量化后单张 24G 卡可跑',
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'qwen3-32b',
    title: 'Qwen3-32B',
    org: '阿里通义千问',
    family: 'Qwen',
    repo: 'Qwen/Qwen3-32B',
    released: '2025-04-28',
    summary: 'Qwen3 里最实用的稠密尺寸，单卡可部署且支持思考/非思考双模式切换。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    vram: 'BF16 需 80G；4bit 单张 24G 可跑',
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'qwen3-30b-a3b',
    title: 'Qwen3-30B-A3B',
    org: '阿里通义千问',
    family: 'Qwen',
    repo: 'Qwen/Qwen3-30B-A3B',
    released: '2025-04-28',
    summary: '总参 30B 只激活 3B 的 MoE，速度快到能在本地当日常助手用。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 3B',
    context: '128K',
    vram: '4bit 量化后单张 16G 卡可跑',
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'qwen3-235b-a22b-2507',
    title: 'Qwen3-235B-A22B-Instruct-2507',
    org: '阿里通义千问',
    family: 'Qwen',
    repo: 'Qwen/Qwen3-235B-A22B-Instruct-2507',
    released: '2025-07-21',
    summary: '2507 版把上下文从 128K 抬到 256K 并去掉思考开关，一个模型直接当通用旗舰用。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 22B',
    context: '256K',
    vram: 'FP8 需 4 卡 H200 级别',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'qwen3-coder-480b-a35b',
    title: 'Qwen3-Coder-480B-A35B',
    org: '阿里通义千问',
    family: 'Qwen',
    repo: 'Qwen/Qwen3-Coder-480B-A35B-Instruct',
    released: '2025-07-22',
    summary: '480B 激活 35B 的代码模型，原生 256K 上下文，把仓库级代码 agent 能力开源了出来。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 35B',
    context: '256K（可扩到 1M）',
    vram: 'FP8 需 8 卡 H200 级别',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'qwen3-coder-30b-a3b',
    title: 'Qwen3-Coder-30B-A3B',
    org: '阿里通义千问',
    family: 'Qwen',
    repo: 'Qwen/Qwen3-Coder-30B-A3B-Instruct',
    released: '2025-07-31',
    summary: '同一代代码模型的小尺寸版，本地 24G 卡就能跑起仓库级补全。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 3B',
    context: '256K',
    vram: '4bit 量化后单张 24G 可跑',
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'qwen3-next-80b-a3b',
    title: 'Qwen3-Next-80B-A3B',
    org: '阿里通义千问',
    family: 'Qwen',
    repo: 'Qwen/Qwen3-Next-80B-A3B-Instruct',
    released: '2025-09-09',
    summary: '用混合线性注意力换效率的下一代架构，80B 只激活 3B，长上下文吞吐比同级稠密模型高一个量级。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 3B',
    context: '256K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'qwen3-vl-235b-a22b',
    title: 'Qwen3-VL-235B-A22B',
    org: '阿里通义千问',
    family: 'Qwen',
    repo: 'Qwen/Qwen3-VL-235B-A22B-Instruct',
    released: '2025-09-22',
    summary: 'Qwen3-VL 的旗舰尺寸，视觉 agent 与长视频理解都能做，可识别图像类目里最强的一档。',
    tags: ['MoE', '可识别图像'],
    commercial: '可商用',
    paramsExtra: '激活 22B',
    context: '256K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'qwen3-vl-8b',
    title: 'Qwen3-VL-8B',
    org: '阿里通义千问',
    family: 'Qwen',
    repo: 'Qwen/Qwen3-VL-8B-Instruct',
    released: '2025-10-11',
    summary: '把视觉语言能力压到 8B 的尺寸，单张消费级卡就能跑截图理解与 OCR。',
    tags: ['Dense', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: '256K',
    vram: 'BF16 单张 24G 可跑',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'qwen3-coder-next',
    title: 'Qwen3-Coder-Next',
    org: '阿里通义千问',
    family: 'Qwen',
    repo: 'Qwen/Qwen3-Coder-Next',
    released: '2026-01-30',
    summary: '接替 Qwen3-Coder 的新一代代码模型，agent 化工具调用与长仓库任务明显更强。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '256K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'qwen3-5-35b-a3b',
    title: 'Qwen3.5-35B-A3B',
    org: '阿里通义千问',
    family: 'Qwen',
    repo: 'Qwen/Qwen3.5-35B-A3B',
    released: '2026-02-24',
    summary: 'Qwen3.5 的中量级 MoE，原生多模态输入，单机就能部署的旗舰级效果。',
    tags: ['MoE', '可识别图像'],
    commercial: '可商用',
    paramsExtra: '激活 3B',
    context: '256K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'qwen3-5-122b-a10b',
    title: 'Qwen3.5-122B-A10B',
    org: '阿里通义千问',
    family: 'Qwen',
    repo: 'Qwen/Qwen3.5-122B-A10B',
    released: '2026-02-24',
    summary: 'Qwen3.5 的 122B 档，激活 10B 换来接近旗舰的效果，是企业自部署的常见落点。',
    tags: ['MoE', '可识别图像'],
    commercial: '可商用',
    paramsExtra: '激活 10B',
    context: '256K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'qwen3-5-27b',
    title: 'Qwen3.5-27B',
    org: '阿里通义千问',
    family: 'Qwen',
    repo: 'Qwen/Qwen3.5-27B',
    released: '2026-02-24',
    summary: 'Qwen3.5 的稠密 27B，单卡可跑且多模态，是本地部署最省心的一档。',
    tags: ['Dense', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: '256K',
    vram: 'BF16 需 80G；8bit 单张 48G 可跑',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'qwen3-6-27b',
    title: 'Qwen3.6-27B',
    org: '阿里通义千问',
    family: 'Qwen',
    repo: 'Qwen/Qwen3.6-27B',
    released: '2026-04-21',
    summary: 'Qwen3.6 代的 27B 稠密模型，编码与 agent 表现比上一代明显提升，依旧 Apache-2.0。',
    tags: ['Dense', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: '256K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'qwen3-8-max',
    title: 'Qwen3.8-Max',
    org: '阿里通义千问',
    family: 'Qwen',
    repo: 'Qwen/Qwen3.8-2.4T-A95B',
    released: '2026-08-08',
    summary: 'Qwen 把旗舰 Max 的文本权重放了出来：2.4T 总参激活 95B，开放权重里的参数天花板。',
    tags: ['MoE', '纯文本'],
    commercial: '有条件可商用',
    paramsExtra: '激活 95B',
    context: '1M',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'qwen3-8-27b',
    title: 'Qwen3.8-27B',
    org: '阿里通义千问',
    family: 'Qwen',
    repo: 'Qwen/Qwen3.8-27B',
    released: '2026-08-14',
    summary: 'Qwen3.8 的 27B 稠密版，发布几天下载就冲到四十多万，端侧与单卡部署的主力。',
    tags: ['Dense', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: '256K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },

  // ------------------------------------------------------------- 智谱 GLM
  {
    slug: 'glm-z1-32b',
    title: 'GLM-Z1-32B',
    org: '智谱 Z.ai',
    family: 'GLM',
    repo: 'zai-org/GLM-Z1-32B-0414',
    released: '2025-04-14',
    summary: '智谱第一代开源推理模型，32B 稠密靠 RL 把数学与代码推理拉到同尺寸领先。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'glm-4-5-air',
    title: 'GLM-4.5-Air',
    org: '智谱 Z.ai',
    family: 'GLM',
    repo: 'zai-org/GLM-4.5-Air',
    released: '2025-07-28',
    summary: 'GLM-4.5 的轻量版：106B 总参只激活 12B，MIT 许可，单机 8 卡就能跑旗舰级效果。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 12B',
    context: '128K',
    vram: 'FP8 需 4 卡 H200 级别',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'glm-4-5v',
    title: 'GLM-4.5V',
    org: '智谱 Z.ai',
    family: 'GLM',
    repo: 'zai-org/GLM-4.5V',
    released: '2025-08-11',
    summary: 'GLM-4.5 的视觉版，把图像与视频理解接进同一套 MoE 里，MIT 许可可商用。',
    tags: ['MoE', '可识别图像'],
    commercial: '可商用',
    paramsExtra: '激活 12B',
    context: '128K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'glm-4-6',
    title: 'GLM-4.6',
    org: '智谱 Z.ai',
    family: 'GLM',
    repo: 'zai-org/GLM-4.6',
    released: '2025-09-30',
    summary: '把上下文拉到 200K 的 GLM 旗舰，代码与 agent 能力在开源里进入第一梯队。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 32B',
    context: '200K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'glm-4-6v',
    title: 'GLM-4.6V',
    org: '智谱 Z.ai',
    family: 'GLM',
    repo: 'zai-org/GLM-4.6V',
    released: '2025-12-08',
    summary: 'GLM-4.6 的多模态版本，把截图/文档理解与代码 agent 合到一个模型里。',
    tags: ['MoE', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: '200K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'glm-4-7-flash',
    title: 'GLM-4.7-Flash',
    org: '智谱 Z.ai',
    family: 'GLM',
    repo: 'zai-org/GLM-4.7-Flash',
    released: '2026-01-19',
    summary: 'GLM-4.7 代的低延迟版本，牺牲一点深度换吞吐，适合当常驻 agent 的执行模型。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '200K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'glm-5-1',
    title: 'GLM-5.1',
    org: '智谱 Z.ai',
    family: 'GLM',
    repo: 'zai-org/GLM-5.1',
    released: '2026-04-03',
    summary: 'GLM-5 代的第一次迭代，长程规划与仓库级重构能力继续加强，仍是 MIT 权重。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 40B',
    context: '200K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'glm-5-3-flash',
    title: 'GLM-5.3-Flash',
    org: '智谱 Z.ai',
    family: 'GLM',
    repo: 'zai-org/GLM-5.3-Flash',
    released: '2026-08-25',
    summary: 'GLM-5.3 的快速版，用更低成本提供同代推理质量，适合高频调用。',
    tags: ['MoE', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: '200K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },

  // --------------------------------------------------------- 月之暗面 Kimi
  {
    slug: 'moonlight-16b-a3b',
    title: 'Moonlight-16B-A3B',
    org: '月之暗面 Moonshot AI',
    family: 'Kimi',
    repo: 'moonshotai/Moonlight-16B-A3B-Instruct',
    released: '2025-02-23',
    summary: 'Kimi 放出的 Muon 优化器验证模型，16B 只激活 3B，训练效率与效果都写进了技术报告。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 3B',
    context: '32K',
    vram: 'BF16 单张 40G 可跑',
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'kimi-vl-a3b',
    title: 'Kimi-VL-A3B',
    org: '月之暗面 Moonshot AI',
    family: 'Kimi',
    repo: 'moonshotai/Kimi-VL-A3B-Instruct',
    released: '2025-04-10',
    summary: 'Kimi 的第一代开源视觉语言模型，激活 3B 就能做长文档与界面理解，MIT 许可。',
    tags: ['MoE', '可识别图像'],
    commercial: '可商用',
    paramsExtra: '激活 3B',
    context: '128K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'kimi-k2-instruct-0905',
    title: 'Kimi-K2-Instruct-0905',
    org: '月之暗面 Moonshot AI',
    family: 'Kimi',
    repo: 'moonshotai/Kimi-K2-Instruct-0905',
    released: '2025-09-05',
    summary: 'K2 的 9 月更新版，把上下文从 128K 扩到 256K 并加强代码 agent，仍是万亿参数级开源模型。',
    tags: ['MoE', '纯文本'],
    commercial: '有条件可商用',
    paramsExtra: '激活 32B',
    context: '256K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'kimi-linear-48b-a3b',
    title: 'Kimi-Linear-48B-A3B',
    org: '月之暗面 Moonshot AI',
    family: 'Kimi',
    repo: 'moonshotai/Kimi-Linear-48B-A3B-Instruct',
    released: '2025-10-30',
    summary: '用混合线性注意力做的长上下文模型，1M 上下文下解码速度几乎不衰减。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 3B',
    context: '1M',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'kimi-k2-7-code',
    title: 'Kimi-K2.7-Code',
    org: '月之暗面 Moonshot AI',
    family: 'Kimi',
    repo: 'moonshotai/Kimi-K2.7-Code',
    released: '2026-06-11',
    summary: 'K2.7 的代码专用版本，面向终端里的长程编码 agent，百万上下文里直接跑仓库任务。',
    tags: ['MoE', '可识别图像'],
    commercial: '有条件可商用',
    paramsExtra: '激活 32B',
    context: '1M',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },

  // ------------------------------------------------------------- MiniMax
  {
    slug: 'minimax-text-01',
    title: 'MiniMax-Text-01',
    org: 'MiniMax',
    family: 'MiniMax',
    repo: 'MiniMaxAI/MiniMax-Text-01',
    released: '2025-01-15',
    summary: '第一个把百万级上下文与线性注意力结合并开源的旗舰，456B 激活 45.9B。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 45.9B',
    context: '1M',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'minimax-vl-01',
    title: 'MiniMax-VL-01',
    org: 'MiniMax',
    family: 'MiniMax',
    repo: 'MiniMaxAI/MiniMax-VL-01',
    released: '2025-01-15',
    summary: 'MiniMax-Text-01 的视觉版本，同一套百万上下文架构上加图像理解。',
    tags: ['MoE', '可识别图像'],
    commercial: '可商用',
    paramsExtra: '激活 45.9B',
    context: '1M',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'minimax-m1-80k',
    title: 'MiniMax-M1-80k',
    org: 'MiniMax',
    family: 'MiniMax',
    repo: 'MiniMaxAI/MiniMax-M1-80k',
    released: '2025-06-16',
    summary: 'MiniMax 的第一个开源推理模型，80K 思维链长度配上百万上下文，Apache-2.0 可商用。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 45.9B',
    context: '1M',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'minimax-m2',
    title: 'MiniMax-M2',
    org: 'MiniMax',
    family: 'MiniMax',
    repo: 'MiniMaxAI/MiniMax-M2',
    released: '2025-10-27',
    summary: '把体量砍到 230B 激活 10B 的 agent 专用模型，用十分之一的成本拿到同代效果。',
    tags: ['MoE', '纯文本'],
    commercial: '有条件可商用',
    paramsExtra: '激活 10B',
    context: '200K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'minimax-m2-5',
    title: 'MiniMax-M2.5',
    org: 'MiniMax',
    family: 'MiniMax',
    repo: 'MiniMaxAI/MiniMax-M2.5',
    released: '2026-02-12',
    summary: 'M2 代的第二次迭代，编码与工具调用稳定性提升，仍是低激活的 MoE 路线。',
    tags: ['MoE', '纯文本'],
    commercial: '有条件可商用',
    paramsExtra: null,
    context: '200K',
    deploys: ['vllm', 'sglang'],
  },

  // ---------------------------------------------------------------- 腾讯混元
  {
    slug: 'hunyuan-a13b',
    title: 'Hunyuan-A13B',
    org: '腾讯混元',
    family: 'Hunyuan',
    repo: 'tencent/Hunyuan-A13B-Instruct',
    released: '2025-06-27',
    summary: '腾讯混元首个开源的 MoE 模型，80B 激活 13B，支持 256K 上下文与双模式推理。',
    tags: ['MoE', '纯文本'],
    commercial: '有条件可商用',
    paramsExtra: '激活 13B',
    context: '256K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'hy3',
    title: 'Hy3',
    org: '腾讯混元',
    family: 'Hunyuan',
    repo: 'tencent/Hy3',
    released: '2026-07-02',
    summary: '腾讯混元第三代开源基座，换成 Apache-2.0 后商用门槛降到最低。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 21B',
    context: '256K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'hy4-preview',
    title: 'Hy4-preview',
    org: '腾讯混元',
    family: 'Hunyuan',
    repo: 'tencent/Hy4-preview',
    released: '2026-08-27',
    summary: '混元第四代的预览版，长程推理与多轮 agent 表现提升，沿用 Apache-2.0。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '256K',
    deploys: ['vllm', 'sglang'],
  },

  // ------------------------------------------------------------------ 华为
  {
    slug: 'openpangu-ultra-moe-718b',
    title: 'openPangu-Ultra-MoE-718B',
    org: '华为',
    family: 'Pangu',
    repo: 'openpangu/openPangu-Ultra-MoE-718B-V1.1',
    released: '2026-03-30',
    summary: '华为盘古的 718B 开源 MoE（权重实测 734B），全流程在昇腾上训练，是国产算力栈里体量最大的开放权重模型。',
    tags: ['MoE', '纯文本'],
    commercial: '有条件可商用',
    paramsExtra: null,
    context: '128K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'openpangu-2-0-pro',
    title: 'openPangu-2.0-Pro',
    org: '华为',
    family: 'Pangu',
    repo: 'openpangu/openPangu-2.0-Pro',
    released: '2026-07-30',
    summary: '盘古 2.0 代的旗舰开放权重版本，连同训练与推理代码一起放出，面向昇腾生态。',
    tags: ['MoE', '纯文本'],
    commercial: '有条件可商用',
    paramsExtra: null,
    context: '512K',
    deploys: ['vllm', 'sglang'],
  },

  // ------------------------------------------------------ 蚂蚁 inclusionAI
  {
    slug: 'ling-lite-1-5',
    title: 'Ling-lite-1.5',
    org: '蚂蚁集团 inclusionAI',
    family: 'Ling',
    repo: 'inclusionAI/Ling-lite-1.5',
    released: '2025-07-23',
    summary: '蚂蚁百灵的轻量 MoE，16.8B 激活 2.75B，MIT 许可下做端侧与高并发场景。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 2.75B',
    context: '32K',
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'ling-flash-2-0',
    title: 'Ling-flash-2.0',
    org: '蚂蚁集团 inclusionAI',
    family: 'Ling',
    repo: 'inclusionAI/Ling-flash-2.0',
    released: '2025-09-17',
    summary: '蚂蚁的第二代主力开源模型，103B 激活 6.1B，用极小激活成本换通用能力。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 6.1B',
    context: '32K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'ring-flash-2-0',
    title: 'Ring-flash-2.0',
    org: '蚂蚁集团 inclusionAI',
    family: 'Ling',
    repo: 'inclusionAI/Ring-flash-2.0',
    released: '2025-09-19',
    summary: 'Ling-flash-2.0 的推理版，把长思维链专门训进模型，MIT 权重可直接商用。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 6.1B',
    context: '32K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'ling-1t',
    title: 'Ling-1T',
    org: '蚂蚁集团 inclusionAI',
    family: 'Ling',
    repo: 'inclusionAI/Ling-1T',
    released: '2025-10-02',
    summary: '蚂蚁首个万亿参数开源基座，激活 50B，MIT 许可把万亿级权重开放出来。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 50B',
    context: '32K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'ring-1t',
    title: 'Ring-1T',
    org: '蚂蚁集团 inclusionAI',
    family: 'Ling',
    repo: 'inclusionAI/Ring-1T',
    released: '2025-10-10',
    summary: 'Ling-1T 的推理版本，万亿 MoE 上做长思维链强化学习，数学与代码成绩突出。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 50B',
    context: '64K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'ling-3-0-flash',
    title: 'Ling-3.0-flash',
    org: '蚂蚁集团 inclusionAI',
    family: 'Ling',
    repo: 'inclusionAI/Ling-3.0-flash',
    released: '2026-08-02',
    summary: '百灵第三代的快速版本，延续极小激活的 MoE 路线，面向高并发 agent 调用。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    deploys: ['vllm', 'sglang'],
  },

  // -------------------------------------------------------------- 美团 LongCat
  {
    slug: 'longcat-flash-chat',
    title: 'LongCat-Flash-Chat',
    org: '美团 LongCat',
    family: 'LongCat',
    repo: 'meituan-longcat/LongCat-Flash-Chat',
    released: '2025-08-30',
    summary: '美团第一次开源基座：560B 激活 27B，用动态激活把推理成本压到同级的三分之一。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 27B',
    context: '128K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'longcat-flash-thinking',
    title: 'LongCat-Flash-Thinking',
    org: '美团 LongCat',
    family: 'LongCat',
    repo: 'meituan-longcat/LongCat-Flash-Thinking',
    released: '2025-09-21',
    summary: 'LongCat-Flash 的推理版本，针对工具调用与长思维链做了专门强化。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 27B',
    context: '128K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'longcat-2-0',
    title: 'LongCat-2.0',
    org: '美团 LongCat',
    family: 'LongCat',
    repo: 'meituan-longcat/LongCat-2.0',
    released: '2026-07-05',
    summary: '1.8T 规模、全程用昇腾 910 训练的开源模型，证明国产算力能撑起万亿级预训练。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    deploys: ['vllm', 'sglang'],
  },

  // ------------------------------------------------------------ 阶跃星辰 Step
  {
    slug: 'step3',
    title: 'Step-3',
    org: '阶跃星辰 StepFun',
    family: 'Step',
    repo: 'stepfun-ai/step3',
    released: '2025-07-25',
    summary: '321B 激活 38B 的多模态推理模型，把图像理解与长思维链放进同一个 MoE。',
    tags: ['MoE', '可识别图像'],
    commercial: '可商用',
    paramsExtra: '激活 38B',
    context: '64K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'step-3-5-flash',
    title: 'Step-3.5-Flash',
    org: '阶跃星辰 StepFun',
    family: 'Step',
    repo: 'stepfun-ai/Step-3.5-Flash',
    released: '2026-02-01',
    summary: 'Step 3.5 代的快速版本，196B 激活 11B，主打低延迟的 agent 与工具调用。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 11B',
    context: '128K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'step-3-7-flash',
    title: 'Step-3.7-Flash',
    org: '阶跃星辰 StepFun',
    family: 'Step',
    repo: 'stepfun-ai/Step-3.7-Flash',
    released: '2026-05-23',
    summary: 'Step 3.7 代的多模态快速版，把截图理解接进低延迟推理链路。',
    tags: ['MoE', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },

  // ---------------------------------------------------------------- 小米 MiMo
  {
    slug: 'mimo-7b-rl',
    title: 'MiMo-7B-RL',
    org: '小米',
    family: 'MiMo',
    repo: 'XiaomiMiMo/MiMo-7B-RL',
    released: '2025-04-30',
    summary: '小米第一个开源推理模型，7B 稠密靠 RL 训练在数学与代码上超过更大的蒸馏模型。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '32K',
    vram: 'BF16 单张 24G 可跑',
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'mimo-vl-7b-rl',
    title: 'MiMo-VL-7B-RL',
    org: '小米',
    family: 'MiMo',
    repo: 'XiaomiMiMo/MiMo-VL-7B-RL',
    released: '2025-05-30',
    summary: 'MiMo 的视觉版本，7B 就能做界面理解与文档问答，MIT 许可可商用。',
    tags: ['Dense', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: '32K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'mimo-v2-flash',
    title: 'MiMo-V2-Flash',
    org: '小米',
    family: 'MiMo',
    repo: 'XiaomiMiMo/MiMo-V2-Flash',
    released: '2025-12-16',
    summary: '小米第一代大尺寸开源 MoE，309B 激活 15B，把端侧经验带到旗舰级推理。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 15B',
    context: '256K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'mimo-v2-5-pro',
    title: 'MiMo-V2.5-Pro',
    org: '小米',
    family: 'MiMo',
    repo: 'XiaomiMiMo/MiMo-V2.5-Pro',
    released: '2026-04-27',
    summary: 'V2.5 代的旗舰档，面向代码与终端 agent 的长程任务，继续 Apache/MIT 宽松许可。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '256K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'mimo-v2-6-pro-rl',
    title: 'MiMo-V2.6-Pro-RL',
    org: '小米',
    family: 'MiMo',
    repo: 'XiaomiMiMo/MiMo-V2.6-Pro-RL',
    released: '2026-09-21',
    summary: 'V2.6 代的强化学习版本，推理链更长更稳，是小米当前最强的开放权重模型。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '256K',
    deploys: ['vllm', 'sglang'],
  },

  // ------------------------------------------------------------ 小红书 dots
  {
    slug: 'dots-llm1',
    title: 'dots.llm1',
    org: '小红书 RedNote',
    family: 'dots',
    repo: 'rednote-hilab/dots.llm1.inst',
    released: '2025-06-05',
    summary: '小红书开源的 142B 激活 14B MoE，训练数据与中间 checkpoint 一并公开，MIT 许可。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 14B',
    context: '128K',
    deploys: ['vllm', 'sglang'],
  },

  // ------------------------------------------------------------- 字节 Seed
  {
    slug: 'seed-coder-8b',
    title: 'Seed-Coder-8B',
    org: '字节跳动 Seed',
    family: 'Seed',
    repo: 'ByteDance-Seed/Seed-Coder-8B-Instruct',
    released: '2025-04-27',
    summary: '字节的 8B 开源代码模型，用模型自己筛数据训出来的，MIT 许可本地可跑。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '32K',
    vram: 'BF16 单张 24G 可跑',
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'seed-oss-36b-base',
    title: 'Seed-OSS-36B-Base',
    org: '字节跳动 Seed',
    family: 'Seed',
    repo: 'ByteDance-Seed/Seed-OSS-36B-Base',
    released: '2025-08-20',
    summary: 'Seed-OSS 的基座版本，512K 上下文，方便团队自己继续做后训练。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '512K',
    deploys: ['vllm', 'sglang'],
  },

  // --------------------------------------------------------------- 百度 ERNIE
  {
    slug: 'ernie-4-5-21b-a3b',
    title: 'ERNIE-4.5-21B-A3B',
    org: '百度',
    family: 'ERNIE',
    repo: 'baidu/ERNIE-4.5-21B-A3B-PT',
    released: '2025-06-30',
    summary: '百度 ERNIE 4.5 开源家族里的中量级 MoE，21B 激活 3B，Apache-2.0 可商用。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 3B',
    context: '128K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'ernie-4-5-vl-424b-a47b',
    title: 'ERNIE-4.5-VL-424B-A47B',
    org: '百度',
    family: 'ERNIE',
    repo: 'baidu/ERNIE-4.5-VL-424B-A47B-PT',
    released: '2025-06-30',
    summary: 'ERNIE 4.5 的异构多模态旗舰，424B 激活 47B，文本与视觉参数分开承载。',
    tags: ['MoE', '可识别图像'],
    commercial: '可商用',
    paramsExtra: '激活 47B',
    context: '128K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },

  // ------------------------------------------------------ 上海 AI Lab InternLM
  {
    slug: 'intern-s1',
    title: 'Intern-S1',
    org: '上海 AI Lab',
    family: 'InternLM',
    repo: 'internlm/Intern-S1',
    released: '2025-07-24',
    summary: '面向科学发现的多模态推理模型，241B 激活 8B，把化学与生物知识专门训了进去。',
    tags: ['MoE', '可识别图像'],
    commercial: '可商用',
    paramsExtra: '激活 8B',
    context: '128K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'internvl3-5-38b',
    title: 'InternVL3.5-38B',
    org: '上海 AI Lab',
    family: 'InternLM',
    repo: 'OpenGVLab/InternVL3_5-38B',
    released: '2025-08-29',
    summary: 'InternVL3.5 的 38B 档，GUI 与文档理解做得扎实，Apache-2.0 可商用。',
    tags: ['Dense', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'intern-s2-397b',
    title: 'Intern-S2-397B',
    org: '上海 AI Lab',
    family: 'InternLM',
    repo: 'internlm/Intern-S2-397B',
    released: '2026-09-13',
    summary: 'Intern-S 科学模型第二代正式版，397B MoE 在科学推理与多模态任务上全面换代。',
    tags: ['MoE', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },

  // ------------------------------------------------------------ 面壁 MiniCPM
  {
    slug: 'minicpm4-8b',
    title: 'MiniCPM4-8B',
    org: '面壁智能',
    family: 'MiniCPM',
    repo: 'openbmb/MiniCPM4-8B',
    released: '2025-06-05',
    summary: '面壁的端侧主力模型，8B 稠密配上稀疏注意力加速，长文本推理明显提速。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '32K',
    vram: 'BF16 单张 24G 可跑',
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'minicpm-v-4-5',
    title: 'MiniCPM-V-4.5',
    org: '面壁智能',
    family: 'MiniCPM',
    repo: 'openbmb/MiniCPM-V-4_5',
    released: '2025-08-26',
    summary: '8B 的端侧视觉语言模型，OCR 与文档问答打得很准，手机级别设备就能跑。',
    tags: ['Dense', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: '32K',
    modalities: ['text', 'image'],
    deploys: ['llama-cpp', 'ollama'],
  },
  {
    slug: 'minicpm5-1b',
    title: 'MiniCPM5-1B',
    org: '面壁智能',
    family: 'MiniCPM',
    repo: 'openbmb/MiniCPM5-1B',
    released: '2026-05-21',
    summary: '1B 级别的第五代端侧模型，把推理能力压进手机与嵌入设备。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '32K',
    vram: '手机端可跑',
    deploys: ['llama-cpp', 'ollama'],
  },

  // ------------------------------------------------------------ 中国电信 TeleAI
  {
    slug: 'telechat3-36b-thinking',
    title: 'TeleChat3-36B-Thinking',
    org: '中国电信 TeleAI',
    family: 'TeleChat',
    repo: 'Tele-AI/TeleChat3-36B-Thinking',
    released: '2025-12-24',
    summary: '中国电信第三代开源模型，36B 带思考模式，面向政务与行业私有化部署。',
    tags: ['Dense', '纯文本'],
    commercial: '有条件可商用',
    paramsExtra: null,
    context: '128K',
    deploys: ['vllm', 'sglang'],
  },

  // ================================================================ 欧美
  // ------------------------------------------------------------------ Meta
  {
    slug: 'llama-4-scout',
    title: 'Llama 4 Scout',
    org: 'Meta',
    family: 'Meta',
    repo: 'meta-llama/Llama-4-Scout-17B-16E-Instruct',
    released: '2025-04-05',
    summary: 'Meta 第一代原生多模态 MoE，16 专家版本把上下文做到 10M，单张 H100 就能跑。',
    tags: ['MoE', '可识别图像'],
    commercial: '有条件可商用',
    paramsExtra: '激活 17B',
    context: '10M',
    vram: '单张 H100 80G（int4）可跑',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },

  // ------------------------------------------------------------ Google Gemma
  {
    slug: 'gemma-3-12b',
    title: 'Gemma 3 12B',
    org: 'Google DeepMind',
    family: 'Google',
    repo: 'google/gemma-3-12b-it',
    released: '2025-03-12',
    summary: 'Gemma 3 的中量级尺寸，单张消费级卡就能跑多模态与 128K 上下文。',
    tags: ['Dense', '可识别图像'],
    commercial: '有条件可商用',
    paramsExtra: null,
    context: '128K',
    vram: 'bf16 单张 24G 可跑',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'gemma-3n-e4b',
    title: 'Gemma 3n E4B',
    org: 'Google DeepMind',
    family: 'Google',
    repo: 'google/gemma-3n-E4B-it',
    released: '2025-06-26',
    summary: '为手机与笔记本设计的 MatFormer 模型，权重 7.8B 但运行时只加载约 4B 有效参数，能吃图、音、文。',
    tags: ['Dense', '可识别图像'],
    commercial: '有条件可商用',
    paramsExtra: null,
    context: '32K',
    vram: '端侧 4G 级内存可跑',
    modalities: ['text', 'image', 'audio'],
    deploys: ['llama-cpp', 'ollama'],
  },
  {
    slug: 'medgemma-27b',
    title: 'MedGemma 27B',
    org: 'Google',
    family: 'Google',
    repo: 'google/medgemma-27b-it',
    released: '2025-07-09',
    summary: '基于 Gemma 3 的医疗专用模型，医学问答与影像报告理解专门调过。',
    tags: ['Dense', '可识别图像'],
    commercial: '有条件可商用',
    paramsExtra: null,
    context: '128K',
    modalities: ['text', 'image'],
    deploys: ['vllm'],
  },
  {
    slug: 'gemma-3-270m',
    title: 'Gemma 3 270M',
    org: 'Google DeepMind',
    family: 'Google',
    repo: 'google/gemma-3-270m',
    released: '2025-08-14',
    summary: '只有 270M 的 Gemma 3，专门给端侧微调与分类任务用，量化后不到 200MB。',
    tags: ['Dense', '纯文本'],
    commercial: '有条件可商用',
    paramsExtra: null,
    context: '32K',
    vram: '手机端可跑',
    deploys: ['llama-cpp', 'ollama'],
  },
  {
    slug: 'gemma-4-31b',
    title: 'Gemma 4 31B',
    org: 'Google DeepMind',
    family: 'Google',
    repo: 'google/gemma-4-31B-it',
    released: '2026-03-11',
    summary: 'Gemma 4 的稠密旗舰，改用 Apache-2.0 后终于可以放心商用，多模态与 agent 能力同代领先。',
    tags: ['Dense', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: '256K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang', 'llama-cpp'],
  },
  {
    slug: 'gemma-4-12b',
    title: 'Gemma 4 12B',
    org: 'Google DeepMind',
    family: 'Google',
    repo: 'google/gemma-4-12B-it',
    released: '2026-05-23',
    summary: 'Gemma 4 的 12B 档，任何输入到任何输出，单卡就能跑的多模态助手。',
    tags: ['Dense', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: '256K',
    vram: 'bf16 单张 32G 可跑',
    modalities: ['text', 'image', 'audio'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'diffusiongemma-26b-a4b',
    title: 'DiffusionGemma 26B-A4B',
    org: 'Google DeepMind',
    family: 'Google',
    repo: 'google/diffusiongemma-26B-A4B-it',
    released: '2026-06-09',
    summary: '用扩散方式生成文本的 Gemma，非自回归解码把吞吐拉高一个量级，Apache-2.0。',
    tags: ['MoE', '可识别图像'],
    commercial: '可商用',
    paramsExtra: '激活 4B',
    context: '128K',
    modalities: ['text', 'image'],
    deploys: ['vllm'],
  },

  // --------------------------------------------------------------- Microsoft
  {
    slug: 'phi-4-mini',
    title: 'Phi-4-mini',
    org: 'Microsoft',
    family: 'Phi',
    repo: 'microsoft/Phi-4-mini-instruct',
    released: '2025-02-26',
    summary: '3.8B 的小模型靠高质量数据在推理上压过更大的同级模型，MIT 许可随便用。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    vram: 'bf16 单张 8G 卡可跑',
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'phi-4-multimodal',
    title: 'Phi-4-multimodal',
    org: 'Microsoft',
    family: 'Phi',
    repo: 'microsoft/Phi-4-multimodal-instruct',
    released: '2025-02-26',
    summary: '5.6B 同时吃文本、图像与语音，是当时最小的开源全模态模型。',
    tags: ['Dense', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    modalities: ['text', 'image', 'audio'],
    deploys: ['vllm'],
  },
  {
    slug: 'phi-4-reasoning',
    title: 'Phi-4-reasoning',
    org: 'Microsoft',
    family: 'Phi',
    repo: 'microsoft/Phi-4-reasoning',
    released: '2025-04-30',
    summary: '把 14B 的 Phi-4 用推理数据继续训练，数学与科学题上追平大几十倍的模型。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '32K',
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },

  // ----------------------------------------------------------------- NVIDIA
  {
    slug: 'nemotron-nano-9b-v2',
    title: 'NVIDIA-Nemotron-Nano-9B-v2',
    org: 'NVIDIA',
    family: 'Nemotron',
    repo: 'nvidia/NVIDIA-Nemotron-Nano-9B-v2',
    released: '2025-08-18',
    summary: 'Mamba-Transformer 混合的 9B 模型，长上下文推理吞吐高，NVIDIA 连训练数据一起放了出来。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    vram: '单张 24G 卡可跑',
    deploys: ['vllm', 'sglang', 'llama-cpp'],
  },
  {
    slug: 'nemotron-3-super-120b-a12b',
    title: 'NVIDIA-Nemotron-3-Super-120B-A12B',
    org: 'NVIDIA',
    family: 'Nemotron',
    repo: 'nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-FP8',
    released: '2026-03-11',
    summary: 'LatentMoE 架构的 120B 激活 12B，原生 NVFP4 预训练，单台 8 卡机就能跑百万上下文。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 12B',
    context: '1M',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'nemotron-3-5-lightning-30b-a3b',
    title: 'NVIDIA-Nemotron-3.5-Lightning-30B-A3B',
    org: 'NVIDIA',
    family: 'Nemotron',
    repo: 'nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16',
    released: '2026-08-01',
    summary: 'Nemotron 3.5 代的轻量档，30B 激活 3B，主打极低延迟的 agent 执行。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 3B',
    context: '1M',
    deploys: ['vllm', 'sglang'],
  },

  // -------------------------------------------------------------------- IBM
  {
    slug: 'granite-4-0-h-1b',
    title: 'Granite 4.0 H 1B',
    org: 'IBM',
    family: 'IBM',
    repo: 'ibm-granite/granite-4.0-h-1b',
    released: '2025-10-07',
    summary: '1B 的混合 Mamba-2 模型，为企业在 CPU 与边缘设备上跑而设计，Apache-2.0。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    vram: 'CPU 即可推理',
    deploys: ['llama-cpp', 'ollama'],
  },
  {
    slug: 'granite-4-1-8b',
    title: 'Granite 4.1 8B',
    org: 'IBM',
    family: 'IBM',
    repo: 'ibm-granite/granite-4.1-8b',
    released: '2026-04-06',
    summary: 'Granite 4.1 的主力尺寸，企业工具调用与 RAG 场景专门优化，许可证依旧宽松。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'granite-4-2-30b',
    title: 'Granite 4.2 30B',
    org: 'IBM',
    family: 'IBM',
    repo: 'ibm-granite/granite-4.2-30b',
    released: '2026-08-07',
    summary: 'Granite 4.2 的 30B 档，进一步强化代码与 agent 能力，仍是全开源权重加宽松许可。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    deploys: ['vllm', 'sglang'],
  },

  // ------------------------------------------------------------------- Ai2
  {
    slug: 'olmo-2-32b',
    title: 'OLMo 2 32B',
    org: 'Allen AI (Ai2)',
    family: 'OLMo',
    repo: 'allenai/OLMo-2-0325-32B-Instruct',
    released: '2025-03-13',
    summary: '完全开源的代表作：权重、训练数据、代码与中间 checkpoint 全都放出来。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '4K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'olmo-3-7b',
    title: 'OLMo 3 7B',
    org: 'Allen AI (Ai2)',
    family: 'OLMo',
    repo: 'allenai/Olmo-3-1025-7B',
    released: '2025-09-12',
    summary: 'OLMo 3 的小尺寸版本，把完整训练流程与 Dolma 3 数据一起公开，适合研究复现。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '64K',
    deploys: ['vllm', 'sglang', 'llama-cpp'],
  },

  // --------------------------------------------------------------- Mistral AI
  {
    slug: 'mistral-small-3-2-24b',
    title: 'Mistral Small 3.2 24B',
    org: 'Mistral AI',
    family: 'Mistral',
    repo: 'mistralai/Mistral-Small-3.2-24B-Instruct-2506',
    released: '2025-06-20',
    summary: '24B 的通用小模型，指令跟随与函数调用经过专门修整，单张 24G 卡就能跑。',
    tags: ['Dense', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    vram: 'bf16 单张 40G 可跑',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'magistral-small-24b',
    title: 'Magistral Small 24B',
    org: 'Mistral AI',
    family: 'Mistral',
    repo: 'mistralai/Magistral-Small-2506',
    released: '2025-06-10',
    summary: 'Mistral 第一个开源推理模型，24B 稠密做多步推理，Apache-2.0 可商用。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'devstral-small-2507',
    title: 'Devstral Small 1.1',
    org: 'Mistral AI',
    family: 'Mistral',
    repo: 'mistralai/Devstral-Small-2507',
    released: '2025-07-10',
    summary: '面向代码 agent 的 24B 模型，能在本地仓库里自己改代码跑测试。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'voxtral-small-24b',
    title: 'Voxtral Small 24B',
    org: 'Mistral AI',
    family: 'Mistral',
    repo: 'mistralai/Voxtral-Small-24B-2507',
    released: '2025-07-15',
    summary: '把语音理解接进语言模型的 24B 版本，长音频转写与问答一步到位。',
    tags: ['Dense', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: '32K',
    modalities: ['text', 'audio'],
    deploys: ['vllm'],
  },
  {
    slug: 'mistral-large-3-675b',
    title: 'Mistral Large 3',
    org: 'Mistral AI',
    family: 'Mistral',
    repo: 'mistralai/Mistral-Large-3-675B-Instruct-2512',
    released: '2025-12-02',
    summary: 'Mistral 第一次把旗舰级 675B 权重开放出来，Apache-2.0 许可，MoE 激活 41B。',
    tags: ['MoE', '可识别图像'],
    commercial: '可商用',
    paramsExtra: '激活 41B',
    context: '256K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'ministral-3-8b',
    title: 'Ministral 3 8B',
    org: 'Mistral AI',
    family: 'Mistral',
    repo: 'mistralai/Ministral-3-8B-Instruct-2512',
    released: '2025-12-02',
    summary: 'Mistral 3 代的小尺寸视觉模型，笔记本上就能跑多模态助手。',
    tags: ['Dense', '可识别图像'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    vram: 'bf16 单张 24G 可跑',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },

  // ------------------------------------------------------------------ OpenAI
  {
    slug: 'gpt-oss-20b',
    title: 'gpt-oss-20b',
    org: 'OpenAI',
    family: 'OpenAI',
    repo: 'openai/gpt-oss-20b',
    released: '2025-08-05',
    summary: 'OpenAI 的 21B 开放权重模型，原生 MXFP4 量化后 16G 显存就能跑。',
    tags: ['MoE', '纯文本'],
    commercial: '可商用',
    paramsExtra: '激活 3.6B',
    context: '128K',
    vram: '16G 显存可跑（原生 MXFP4）',
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },

  // ------------------------------------------------------------------- TII
  {
    slug: 'falcon-h1-34b',
    title: 'Falcon-H1-34B',
    org: 'TII 技术创新研究院',
    family: 'Falcon',
    repo: 'tiiuae/Falcon-H1-34B-Instruct',
    released: '2025-05-20',
    summary: '并行 Attention + Mamba-2 的混合架构，34B 支持 18 种语言与 256K 上下文。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '256K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'falcon-h1r-7b',
    title: 'Falcon-H1R-7B',
    org: 'TII 技术创新研究院',
    family: 'Falcon',
    repo: 'tiiuae/Falcon-H1R-7B',
    released: '2025-10-29',
    summary: '7B 的推理模型，在同尺寸里推理成绩领先，Apache 系许可可商用。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '128K',
    vram: '单张 24G 卡可跑',
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },

  // ------------------------------------------------------------------ 其他
  {
    slug: 'smollm3-3b',
    title: 'SmolLM3-3B',
    org: 'Hugging Face',
    family: 'SmolLM',
    repo: 'HuggingFaceTB/SmolLM3-3B',
    released: '2025-07-08',
    summary: '3B 的全开源小模型，训练配方与数据都公开，支持思考/非思考双模式与六种语言。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '64K',
    vram: '量化后手机可跑',
    deploys: ['llama-cpp', 'ollama'],
  },
  {
    slug: 'apertus-70b',
    title: 'Apertus-70B',
    org: 'Swiss AI Initiative',
    family: 'Apertus',
    repo: 'swiss-ai/Apertus-70B-Instruct-2509',
    released: '2025-09-01',
    summary: '瑞士国家级开源模型，权重、数据与配方全公开，并尊重网页抓取的退出声明。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '64K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'exaone-4-0-32b',
    title: 'EXAONE 4.0 32B',
    org: 'LG AI Research',
    family: 'EXAONE',
    repo: 'LGAI-EXAONE/EXAONE-4.0-32B',
    released: '2025-07-15',
    summary: 'LG 的混合推理模型，32B 支持思考与非思考模式，许可证只允许研究用途。',
    tags: ['Dense', '纯文本'],
    commercial: '不可商用',
    paramsExtra: null,
    context: '128K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'solar-open-100b',
    title: 'Solar-Open-100B',
    org: 'Upstage',
    family: 'Solar',
    repo: 'upstage/Solar-Open-100B',
    released: '2025-12-10',
    summary: '韩国政府自主 AI 项目的首个成果，从零训练的 100B MoE，韩语能力突出。',
    tags: ['MoE', '纯文本'],
    commercial: '有条件可商用',
    paramsExtra: null,
    context: '128K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'k-exaone-236b-a23b',
    title: 'K-EXAONE-236B-A23B',
    org: 'LG AI Research',
    family: 'EXAONE',
    repo: 'LGAI-EXAONE/K-EXAONE-236B-A23B',
    released: '2025-12-26',
    summary: 'LG 与韩国政府合作的 236B MoE，激活 23B，主打韩语与多语言企业场景。',
    tags: ['MoE', '纯文本'],
    commercial: '不可商用',
    paramsExtra: '激活 23B',
    context: '128K',
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'jamba-reasoning-3b',
    title: 'AI21 Jamba Reasoning 3B',
    org: 'AI21 Labs',
    family: 'Jamba',
    repo: 'ai21labs/AI21-Jamba-Reasoning-3B',
    released: '2025-10-05',
    summary: '混合 SSM-Transformer 的 3B 推理模型，长上下文吞吐好，Apache-2.0 可商用。',
    tags: ['Dense', '纯文本'],
    commercial: '可商用',
    paramsExtra: null,
    context: '256K',
    vram: '单张 16G 卡可跑',
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'tiny-aya-global',
    title: 'Tiny Aya Global',
    org: 'Cohere Labs',
    family: 'Aya',
    repo: 'CohereLabs/tiny-aya-global',
    released: '2026-02-13',
    summary: '覆盖 70 多种语言的端侧小模型，把多语言覆盖做到手机可跑的程度。',
    tags: ['Dense', '纯文本'],
    commercial: '不可商用',
    paramsExtra: null,
    context: '128K',
    vram: '端侧可跑',
    deploys: ['llama-cpp', 'ollama'],
  },
  {
    slug: 'command-a-plus-05-2026',
    title: 'Command A+',
    org: 'Cohere',
    family: 'Command',
    repo: 'CohereLabs/command-a-plus-05-2026-bf16',
    released: '2026-05-11',
    summary: 'Cohere 的旗舰开放权重模型，218B 激活 25B，面向企业 RAG 与多语言检索。',
    tags: ['MoE', '可识别图像'],
    commercial: '不可商用',
    paramsExtra: '激活 25B',
    context: '192K',
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'north-mini-code-1-0',
    title: 'North Mini Code 1.0',
    org: 'Cohere',
    family: 'Command',
    repo: 'CohereLabs/North-Mini-Code-1.0',
    released: '2026-06-05',
    summary: 'Cohere 面向编码 agent 的小尺寸模型，能在本地仓库里做补全与重构。',
    tags: ['Dense', '纯文本'],
    commercial: '不可商用',
    paramsExtra: null,
    context: '128K',
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },

  // ===== 第二批补录（2026-10，按「只收大尺寸与主流版本」口径筛出）=====
  {
    slug: 'qwen3-8-flash-next',
    title: "Qwen3.8-Flash-Next",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3.8-Flash-Next',
    released: '2026-08-24',
    verified: true,
    summary: "Qwen3.8 代的轻量旗舰，180B 激活 6B，把 Max 的能力压到单机可部署的体量。",
    tags: ['Dense', '可识别图像'],
    license: "other",
    commercial: '可商用',
    context: "1M",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'qwen3-5-9b',
    title: "Qwen3.5-9B",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3.5-9B',
    released: '2026-02-27',
    verified: true,
    summary: "Qwen3.5 代的 9B 稠密版，单张 24G 卡可跑的多模态助手。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "256K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'qwen3-5-4b',
    title: "Qwen3.5-4B",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3.5-4B',
    released: '2026-02-27',
    verified: true,
    summary: "Qwen3.5 代的 4B 稠密版，端侧与轻量部署的主力尺寸。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "256K",
    modalities: ['text', 'image'],
    deploys: ['llama-cpp', 'ollama'],
  },
  {
    slug: 'qwen3-6-35b-a3b',
    title: "Qwen3.6-35B-A3B",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3.6-35B-A3B',
    released: '2026-04-15',
    verified: true,
    summary: "Qwen3.6 代的中量级 MoE，35B 激活 3B，多模态输入本地就能跑。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "256K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'qwen3-vl-32b-instruct',
    title: "Qwen3-VL-32B-Instruct",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3-VL-32B-Instruct',
    released: '2025-10-19',
    verified: true,
    summary: "Qwen3-VL 的 32B 指令版，视觉 agent 与长文档理解在单机尺寸里最强的一档。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "256K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'qwen3-vl-4b-instruct',
    title: "Qwen3-VL-4B-Instruct",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3-VL-4B-Instruct',
    released: '2025-10-11',
    verified: true,
    summary: "Qwen3-VL 的 4B 版本，消费级显卡就能跑截图理解与 OCR。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "256K",
    modalities: ['text', 'image'],
    deploys: ['llama-cpp', 'ollama'],
  },
  {
    slug: 'qwen3-vl-8b-thinking',
    title: "Qwen3-VL-8B-Thinking",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3-VL-8B-Thinking',
    released: '2025-10-11',
    verified: true,
    summary: "Qwen3-VL 8B 的思考版，用长思维链做图像推理与界面定位。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "256K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'qwen3-vl-30b-a3b-instruct',
    title: "Qwen3-VL-30B-A3B-Instruct",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3-VL-30B-A3B-Instruct',
    released: '2025-09-30',
    verified: true,
    summary: "Qwen3-VL 的 30B 激活 3B 版本，多模态吞吐与成本最平衡的一档。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "256K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'qwen3-vl-4b-thinking',
    title: "Qwen3-VL-4B-Thinking",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3-VL-4B-Thinking',
    released: '2025-10-11',
    verified: true,
    summary: "Qwen3-VL 4B 的思考版，小尺寸上也保留视觉推理链。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "256K",
    modalities: ['text', 'image'],
    deploys: ['llama-cpp', 'ollama'],
  },
  {
    slug: 'qwen3-vl-30b-a3b-thinking',
    title: "Qwen3-VL-30B-A3B-Thinking",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3-VL-30B-A3B-Thinking',
    released: '2025-09-30',
    verified: true,
    summary: "同 30B-A3B 的思考版，把视觉推理链接进低激活的 MoE。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "256K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'qwen3-vl-235b-a22b-thinking',
    title: "Qwen3-VL-235B-A22B-Thinking",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3-VL-235B-A22B-Thinking',
    released: '2025-09-22',
    verified: true,
    summary: "Qwen3-VL 旗舰的思考版，长视频与复杂图表推理的开源上限。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "256K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'qwen3-235b-a22b-thinking-2507',
    title: "Qwen3-235B-A22B-Thinking-2507",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3-235B-A22B-Thinking-2507',
    released: '2025-07-25',
    verified: true,
    summary: "235B 旗舰的 2507 思考版，长思维链质量比 4 月首发版明显提升。",
    tags: ['MoE', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "256K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'qwen3-omni-30b-a3b-thinking',
    title: "Qwen3-Omni-30B-A3B-Thinking",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3-Omni-30B-A3B-Thinking',
    released: '2025-09-15',
    verified: true,
    summary: "Qwen3-Omni 的思考版，文本 / 图像 / 音频统一进一个模型并带推理链。",
    tags: ['Dense', '可识别图像'],
    license: "other",
    commercial: '可商用',
    context: "128K",
    modalities: ['text', 'image', 'audio'],
    deploys: ['vllm'],
  },
  {
    slug: 'qwen3-30b-a3b-instruct-2507',
    title: "Qwen3-30B-A3B-Instruct-2507",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3-30B-A3B-Instruct-2507',
    released: '2025-07-28',
    verified: true,
    summary: "30B-A3B 的 2507 指令版，上下文扩到 256K，本地部署的主流选择。",
    tags: ['MoE', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "256K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'qwen3-30b-a3b-thinking-2507',
    title: "Qwen3-30B-A3B-Thinking-2507",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3-30B-A3B-Thinking-2507',
    released: '2025-07-29',
    verified: true,
    summary: "30B-A3B 的 2507 思考版，小激活量下保留完整推理链。",
    tags: ['MoE', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "256K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'qwen3-4b-instruct-2507',
    title: "Qwen3-4B-Instruct-2507",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3-4B-Instruct-2507',
    released: '2025-08-05',
    verified: true,
    summary: "Qwen3 的 4B 指令版，4B 尺寸里通用的本地助手首选。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "256K",
    modalities: ['text'],
    deploys: ['llama-cpp', 'ollama'],
  },
  {
    slug: 'qwen3-4b-thinking-2507',
    title: "Qwen3-4B-Thinking-2507",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3-4B-Thinking-2507',
    released: '2025-08-05',
    verified: true,
    summary: "Qwen3 4B 的思考版，端侧也能跑推理链。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "256K",
    modalities: ['text'],
    deploys: ['llama-cpp', 'ollama'],
  },
  {
    slug: 'qwen3-14b',
    title: "Qwen3-14B",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3-14B',
    released: '2025-04-27',
    verified: true,
    summary: "Qwen3 的 14B 稠密版，单卡可跑且思考 / 非思考双模式。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'qwen3-4b',
    title: "Qwen3-4B",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3-4B',
    released: '2025-04-27',
    verified: true,
    summary: "Qwen3 的 4B 稠密版，手机与开发板级别的部署选择。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['llama-cpp', 'ollama'],
  },
  {
    slug: 'qwen3-8b',
    title: "Qwen3-8B",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen3-8B',
    released: '2025-04-27',
    verified: true,
    summary: "Qwen3 的 8B 稠密版，下载量最大的开源尺寸之一。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'qwen2-5-omni-7b',
    title: "Qwen2.5-Omni-7B",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen2.5-Omni-7B',
    released: '2025-03-22',
    verified: true,
    summary: "Qwen2.5 时代的端到端全模态模型，文本 / 图像 / 音频 / 视频一个模型吃下。",
    tags: ['Dense', '可识别图像'],
    license: "other",
    commercial: '可商用',
    context: "32K",
    modalities: ['text', 'image', 'audio'],
    deploys: ['vllm'],
  },
  {
    slug: 'qwen2-5-vl-7b-instruct',
    title: "Qwen2.5-VL-7B-Instruct",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen2.5-VL-7B-Instruct',
    released: '2025-01-26',
    verified: true,
    summary: "Qwen2.5-VL 的 7B 版本，文档解析与视觉定位在本地尺寸里口碑最好。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'qwen2-5-vl-32b-instruct',
    title: "Qwen2.5-VL-32B-Instruct",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen2.5-VL-32B-Instruct',
    released: '2025-03-21',
    verified: true,
    summary: "Qwen2.5-VL 补上的 32B 中量级尺寸，效果逼近 72B 而显存要求低一半。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'qwen2-5-vl-3b-instruct',
    title: "Qwen2.5-VL-3B-Instruct",
    org: "阿里通义千问",
    family: "Qwen",
    repo: 'Qwen/Qwen2.5-VL-3B-Instruct',
    released: '2025-01-26',
    verified: true,
    summary: "Qwen2.5-VL 的 3B 版本，端侧做 OCR 与界面理解最省资源的一档。",
    tags: ['Dense', '可识别图像'],
    commercial: '有条件可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['llama-cpp', 'ollama'],
  },
  {
    slug: 'gemma-3-4b-it',
    title: "Gemma 3 4B",
    org: "Google DeepMind",
    family: "Google",
    repo: 'google/gemma-3-4b-it',
    released: '2025-02-20',
    verified: true,
    summary: "Gemma 3 的 4B 多模态版本，笔记本与单张消费卡就能跑。",
    tags: ['Dense', '可识别图像'],
    license: "Gemma Terms of Use",
    commercial: '有条件可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['llama-cpp', 'ollama'],
  },
  {
    slug: 'gemma-4-26b-a4b',
    title: "Gemma 4 26B A4B（基座）",
    org: "Google DeepMind",
    family: "Google",
    repo: 'google/gemma-4-26B-A4B',
    released: '2026-03-12',
    verified: true,
    summary: "Gemma 4 的 26B 激活 4B MoE 基座，为二次训练与蒸馏准备。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "256K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'gemma-4-e4b-it',
    title: "Gemma 4 E4B",
    org: "Google DeepMind",
    family: "Google",
    repo: 'google/gemma-4-E4B-it',
    released: '2026-03-02',
    verified: true,
    summary: "Gemma 4 的端侧档，运行时只加载约 4B 有效参数，手机就能跑多模态。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text', 'image', 'audio'],
    deploys: ['llama-cpp', 'ollama'],
  },
  {
    slug: 'phi-4-reasoning-plus',
    title: "Phi-4-reasoning-plus",
    org: "Microsoft",
    family: "Phi",
    repo: 'microsoft/Phi-4-reasoning-plus',
    released: '2025-04-17',
    verified: true,
    summary: "Phi-4-reasoning 的加强版，用更多 RL 换更长的推理链与更高数学成绩。",
    tags: ['Dense', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "32K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'phi-4-mini-reasoning',
    title: "Phi-4-mini-reasoning",
    org: "Microsoft",
    family: "Phi",
    repo: 'microsoft/Phi-4-mini-reasoning',
    released: '2025-04-29',
    verified: true,
    summary: "把推理能力压到 3.8B 的版本，端侧做数学与逻辑题。",
    tags: ['Dense', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'phi-4-reasoning-vision-15b',
    title: "Phi-4-reasoning-vision-15B",
    org: "Microsoft",
    family: "Phi",
    repo: 'microsoft/Phi-4-reasoning-vision-15B',
    released: '2026-01-23',
    verified: true,
    summary: "Phi-4 的视觉推理版本，看图做题与图表理解在 15B 尺寸里表现突出。",
    tags: ['Dense', '可识别图像'],
    license: "MIT",
    commercial: '可商用',
    context: "32K",
    modalities: ['text', 'image'],
    deploys: ['vllm'],
  },
  {
    slug: 'phi-4-mini-flash-reasoning',
    title: "Phi-4-mini-flash-reasoning",
    org: "Microsoft",
    family: "Phi",
    repo: 'microsoft/Phi-4-mini-flash-reasoning',
    released: '2025-06-19',
    verified: true,
    summary: "Decoder 与扩散混合的推理小模型，解码速度比同尺寸自回归模型快数倍。",
    tags: ['Dense', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "64K",
    modalities: ['text'],
    deploys: ['vllm'],
  },
  {
    slug: 'nvidia-nemotron-3-nano-30b-a3b-bf16',
    title: "NVIDIA-Nemotron-3-Nano-30B-A3B-BF16",
    org: "NVIDIA",
    family: "Nemotron",
    repo: 'nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16',
    released: '2025-12-04',
    verified: true,
    summary: "Nemotron 3 Nano 的 BF16 权重版，混合 Mamba-Transformer 的 30B 激活 3B。",
    tags: ['MoE', '纯文本'],
    license: "other",
    commercial: '可商用',
    context: "1M",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'nvidia-nemotron-nano-12b-v2',
    title: "NVIDIA-Nemotron-Nano-12B-v2",
    org: "NVIDIA",
    family: "Nemotron",
    repo: 'nvidia/NVIDIA-Nemotron-Nano-12B-v2',
    released: '2025-08-21',
    verified: true,
    summary: "Nemotron Nano 的 12B 视觉版，混合 Mamba 架构加图像输入。",
    tags: ['Dense', '可识别图像'],
    license: "other",
    commercial: '可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'nvidia-nemotron-3-super-120b-a12b-bf16',
    title: "NVIDIA-Nemotron-3-Super-120B-A12B-BF16",
    org: "NVIDIA",
    family: "Nemotron",
    repo: 'nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-BF16',
    released: '2026-03-10',
    verified: true,
    summary: "Nemotron 3 Super 的 BF16 权重版，LatentMoE 加多 token 预测的旗舰档。",
    tags: ['MoE', '纯文本'],
    license: "other",
    commercial: '可商用',
    context: "1M",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'nvidia-nemotron-nano-9b-v2-japanese',
    title: "NVIDIA-Nemotron-Nano-9B-v2-Japanese",
    org: "NVIDIA",
    family: "Nemotron",
    repo: 'nvidia/NVIDIA-Nemotron-Nano-9B-v2-Japanese',
    released: '2026-02-04',
    verified: true,
    summary: "Nemotron Nano 9B 的日语特化版，面向日本企业的本地化部署。",
    tags: ['Dense', '纯文本'],
    license: "other",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm'],
  },
  {
    slug: 'nemotron-cascade-2-30b-a3b',
    title: "Nemotron-Cascade-2-30B-A3B",
    org: "NVIDIA",
    family: "Nemotron",
    repo: 'nvidia/Nemotron-Cascade-2-30B-A3B',
    released: '2026-03-18',
    verified: true,
    summary: "级联式推理的 30B 实验模型，把简单问题交给小模型、难题再上大模型。",
    tags: ['MoE', '纯文本'],
    license: "other",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm'],
  },
  {
    slug: 'nemotron-labs-diffusion-14b',
    title: "Nemotron-Labs-Diffusion-14B",
    org: "NVIDIA",
    family: "Nemotron",
    repo: 'nvidia/Nemotron-Labs-Diffusion-14B',
    released: '2026-04-22',
    verified: true,
    summary: "扩散式文本生成模型，同一份权重支持自回归 / 扩散 / 自推测三种解码。",
    tags: ['Dense', '纯文本'],
    license: "other",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm'],
  },
  {
    slug: 'llama-4-scout-17b-16e',
    title: "Llama 4 Scout（基座）",
    org: "Meta",
    family: "Meta",
    repo: 'meta-llama/Llama-4-Scout-17B-16E',
    released: '2025-04-02',
    verified: true,
    summary: "Llama 4 Scout 的预训练基座，为自建后训练与蒸馏提供起点。",
    tags: ['Dense', '可识别图像'],
    license: "other",
    commercial: '可商用',
    context: "10M",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'mistral-small-24b-instruct-2501',
    title: "Mistral-Small-24B-Instruct-2501",
    org: "Mistral AI",
    family: "Mistral",
    repo: 'mistralai/Mistral-Small-24B-Instruct-2501',
    released: '2025-01-28',
    verified: true,
    summary: "Mistral Small 3 的首发版本，24B 稠密以低延迟见长，Apache-2.0 可商用。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "32K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'mistral-small-4-119b-2603',
    title: "Mistral-Small-4-119B-2603",
    org: "Mistral AI",
    family: "Mistral",
    repo: 'mistralai/Mistral-Small-4-119B-2603',
    released: '2026-01-23',
    verified: true,
    summary: "Mistral Small 4 代：119B 激活 7B 的 MoE，把旗舰能力压到单机可跑。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "256K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'mistral-medium-3-5-128b',
    title: "Mistral-Medium-3.5-128B",
    org: "Mistral AI",
    family: "Mistral",
    repo: 'mistralai/Mistral-Medium-3.5-128B',
    released: '2026-03-31',
    verified: true,
    summary: "Mistral Medium 首次放权重，128B 稠密面向企业私有化部署。",
    tags: ['Dense', '纯文本'],
    license: "other",
    commercial: '可商用',
    context: "256K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'devstral-2-123b-instruct-2512',
    title: "Devstral-2-123B-Instruct-2512",
    org: "Mistral AI",
    family: "Mistral",
    repo: 'mistralai/Devstral-2-123B-Instruct-2512',
    released: '2025-11-28',
    verified: true,
    summary: "Devstral 2 的大尺寸版本，123B 面向长程编码 agent。",
    tags: ['Dense', '纯文本'],
    license: "other",
    commercial: '可商用',
    context: "256K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'devstral-small-2-24b-instruct-2512',
    title: "Devstral-Small-2-24B-Instruct-2512",
    org: "Mistral AI",
    family: "Mistral",
    repo: 'mistralai/Devstral-Small-2-24B-Instruct-2512',
    released: '2025-11-28',
    verified: true,
    summary: "Devstral 第二代的 24B 版本，SWE 类仓库任务成绩在同尺寸领先。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'ministral-3-14b-reasoning-2512',
    title: "Ministral-3-14B-Reasoning-2512",
    org: "Mistral AI",
    family: "Mistral",
    repo: 'mistralai/Ministral-3-14B-Reasoning-2512',
    released: '2025-10-31',
    verified: true,
    summary: "Ministral 3 的 14B 思考版，小尺寸上做多步推理。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'ministral-3-14b-instruct-2512',
    title: "Ministral-3-14B-Instruct-2512",
    org: "Mistral AI",
    family: "Mistral",
    repo: 'mistralai/Ministral-3-14B-Instruct-2512',
    released: '2025-10-31',
    verified: true,
    summary: "Ministral 3 的 14B 指令版，单卡可跑的多模态小模型。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'magistral-small-2509',
    title: "Magistral-Small-2509",
    org: "Mistral AI",
    family: "Mistral",
    repo: 'mistralai/Magistral-Small-2509',
    released: '2025-09-12',
    verified: true,
    summary: "Magistral Small 的 2509 版本，多语言推理与可追溯推理轨迹。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'granite-3-2-8b-instruct',
    title: "Granite 3.2 8B",
    org: "IBM",
    family: "IBM",
    repo: 'ibm-granite/granite-3.2-8b-instruct',
    released: '2025-02-17',
    verified: true,
    summary: "Granite 3.2 的 8B 版本，第一次把 thinking 开关带进企业小模型。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'granite-4-1-30b',
    title: "Granite 4.1 30B",
    org: "IBM",
    family: "IBM",
    repo: 'ibm-granite/granite-4.1-30b',
    released: '2026-04-06',
    verified: true,
    summary: "Granite 4.1 的 30B 版本，企业级长上下文与 agent 能力的主力档。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'granite-3-3-8b-instruct',
    title: "Granite 3.3 8B",
    org: "IBM",
    family: "IBM",
    repo: 'ibm-granite/granite-3.3-8b-instruct',
    released: '2025-04-09',
    verified: true,
    summary: "Granite 3.3 的 8B 版本，工具调用与 RAG 场景专门加强。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'granite-vision-4-1-4b',
    title: "Granite Vision 4.1 4B",
    org: "IBM",
    family: "IBM",
    repo: 'ibm-granite/granite-vision-4.1-4b',
    released: '2026-04-16',
    verified: true,
    summary: "Granite 4.1 的视觉版本，4B 做文档与图表理解。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'granite-4-2-8b',
    title: "Granite 4.2 8B",
    org: "IBM",
    family: "IBM",
    repo: 'ibm-granite/granite-4.2-8b',
    released: '2026-08-07',
    verified: true,
    summary: "Granite 4.2 的 8B 版本，强化代码与推理的小尺寸企业模型。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'olmo-3-7b-think',
    title: "Olmo-3-7B-Think",
    org: "Allen AI (Ai2)",
    family: "OLMo",
    repo: 'allenai/Olmo-3-7B-Think',
    released: '2025-11-18',
    verified: true,
    summary: "OLMo 3 7B 的思考版，可复现的推理模型训练流程。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "64K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'olmo-3-1-32b-think',
    title: "Olmo-3.1-32B-Think",
    org: "Allen AI (Ai2)",
    family: "OLMo",
    repo: 'allenai/Olmo-3.1-32B-Think',
    released: '2025-12-10',
    verified: true,
    summary: "OLMo 3.1 的 32B 思考版，完全开源路线上的旗舰推理尺寸。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "64K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'olmo-3-7b-instruct',
    title: "Olmo-3-7B-Instruct",
    org: "Allen AI (Ai2)",
    family: "OLMo",
    repo: 'allenai/Olmo-3-7B-Instruct',
    released: '2025-11-19',
    verified: true,
    summary: "OLMo 3 7B 的指令版，连同 Dolma 3 数据与训练代码一起公开。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "64K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'olmo-3-1125-32b',
    title: "OLMo 3 32B（1125 基座）",
    org: "Allen AI (Ai2)",
    family: "OLMo",
    repo: 'allenai/Olmo-3-1125-32B',
    released: '2025-11-04',
    verified: true,
    summary: "OLMo 3 的 32B 基座（11 月 25 日版），用于复现与二次训练。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "64K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'deepseek-v3-0324',
    title: "DeepSeek-V3-0324",
    org: "DeepSeek 深度求索",
    family: "DeepSeek",
    repo: 'deepseek-ai/DeepSeek-V3-0324',
    released: '2025-03-24',
    verified: true,
    summary: "V3 的 3 月升级版，推理与前端代码明显变强，仍是 MIT 的 671B MoE。",
    tags: ['MoE', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'deepseek-v3-1-terminus',
    title: "DeepSeek-V3.1-Terminus",
    org: "DeepSeek 深度求索",
    family: "DeepSeek",
    repo: 'deepseek-ai/DeepSeek-V3.1-Terminus',
    released: '2025-09-22',
    verified: true,
    summary: "V3.1 的 Terminus 版，把中英语言一致性与 agent 稳定性修了一轮。",
    tags: ['MoE', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'deepseek-v3-2-speciale',
    title: "DeepSeek-V3.2-Speciale",
    org: "DeepSeek 深度求索",
    family: "DeepSeek",
    repo: 'deepseek-ai/DeepSeek-V3.2-Speciale',
    released: '2025-11-28',
    verified: true,
    summary: "V3.2 的长思考特化版，把推理链拉到极限而不追求吞吐。",
    tags: ['MoE', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'deepseek-r1-0528',
    title: "DeepSeek-R1-0528",
    org: "DeepSeek 深度求索",
    family: "DeepSeek",
    repo: 'deepseek-ai/DeepSeek-R1-0528',
    released: '2025-05-28',
    verified: true,
    summary: "R1 的 5 月更新版，把思考深度与代码能力再推一档，MIT 许可。",
    tags: ['MoE', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'deepseek-v4-pro-0813',
    title: "DeepSeek-V4-Pro-0813",
    org: "DeepSeek 深度求索",
    family: "DeepSeek",
    repo: 'deepseek-ai/DeepSeek-V4-Pro-0813',
    released: '2026-08-13',
    verified: true,
    summary: "V4-Pro 的 8 月更新版，长程 agent 与仓库级任务继续加强。",
    tags: ['MoE', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "1M",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'deepseek-v4-flash-vision-exp',
    title: "DeepSeek-V4-Flash-Vision-Exp",
    org: "DeepSeek 深度求索",
    family: "DeepSeek",
    repo: 'deepseek-ai/DeepSeek-V4-Flash-Vision-Exp',
    released: '2026-08-31',
    verified: true,
    summary: "V4-Flash 的视觉实验版，第一次给这条线接上图像输入。",
    tags: ['MoE', '可识别图像'],
    license: "MIT",
    commercial: '可商用',
    context: "1M",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'deepseek-r1-zero',
    title: "DeepSeek-R1-Zero",
    org: "DeepSeek 深度求索",
    family: "DeepSeek",
    repo: 'deepseek-ai/DeepSeek-R1-Zero',
    released: '2025-01-20',
    verified: true,
    summary: "不做 SFT、纯强化学习训出来的 R1-Zero，是整套推理路线的原始实验样本。",
    tags: ['MoE', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'janus-pro-7b',
    title: "Janus-Pro-7B",
    org: "DeepSeek 深度求索",
    family: "DeepSeek",
    repo: 'deepseek-ai/Janus-Pro-7B',
    released: '2025-01-26',
    verified: true,
    summary: "把图像理解与图像生成解耦到两条路径的统一模型，7B 就能双向做。",
    tags: ['Dense', '可识别图像'],
    license: "MIT",
    commercial: '可商用',
    context: "32K",
    modalities: ['text', 'image'],
    deploys: ['vllm'],
  },
  {
    slug: 'glm-4-32b-0414',
    title: "GLM-4-32B-0414",
    org: "智谱 Z.ai",
    family: "GLM",
    repo: 'zai-org/GLM-4-32B-0414',
    released: '2025-04-07',
    verified: true,
    summary: "GLM-4 的 32B 稠密版，0414 批次的基座模型，MIT 许可。",
    tags: ['Dense', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "32K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'glm-4-1v-9b-thinking',
    title: "GLM-4.1V-9B-Thinking",
    org: "智谱 Z.ai",
    family: "GLM",
    repo: 'zai-org/GLM-4.1V-9B-Thinking',
    released: '2025-06-28',
    verified: true,
    summary: "GLM-4.1V 的 9B 视觉思考版，小尺寸做图表与界面推理。",
    tags: ['Dense', '可识别图像'],
    license: "MIT",
    commercial: '可商用',
    context: "64K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'glm-z1-rumination-32b-0414',
    title: "GLM-Z1-Rumination-32B-0414",
    org: "智谱 Z.ai",
    family: "GLM",
    repo: 'zai-org/GLM-Z1-Rumination-32B-0414',
    released: '2025-04-13',
    verified: true,
    summary: "GLM-Z1 的沉思版本，先想清楚再答，面向复杂研究型问题。",
    tags: ['Dense', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "32K",
    modalities: ['text'],
    deploys: ['vllm'],
  },
  {
    slug: 'minimax-m2-1',
    title: "MiniMax-M2.1",
    org: "MiniMax",
    family: "MiniMax",
    repo: 'MiniMaxAI/MiniMax-M2.1',
    released: '2025-12-20',
    verified: true,
    summary: "M2 代的第一次迭代，编码与工具调用稳定性提升。",
    tags: ['MoE', '纯文本'],
    license: "other",
    commercial: '可商用',
    context: "200K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'hunyuan-7b-instruct',
    title: "Hunyuan-7B",
    org: "腾讯混元",
    family: "Hunyuan",
    repo: 'tencent/Hunyuan-7B-Instruct',
    released: '2025-07-30',
    verified: true,
    summary: "混元稠密系列的 7B 指令版，端侧与高并发场景的开源选择。",
    tags: ['Dense', '纯文本'],
    license: "Tencent Hunyuan Community License",
    commercial: '有条件可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'minimax-m2-7',
    title: "MiniMax-M2.7",
    org: "MiniMax",
    family: "MiniMax",
    repo: 'MiniMaxAI/MiniMax-M2.7',
    released: '2026-04-09',
    verified: true,
    summary: "M2 代的第三次迭代，激活仍只 10B，面向长程 agent 调用。",
    tags: ['MoE', '纯文本'],
    license: "other",
    commercial: '可商用',
    context: "200K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'glm-4-6v-flash',
    title: "GLM-4.6V-Flash",
    org: "智谱 Z.ai",
    family: "GLM",
    repo: 'zai-org/GLM-4.6V-Flash',
    released: '2025-12-07',
    verified: true,
    summary: "GLM-4.6V 的快速视觉版，低延迟跑截图理解与文档问答。",
    tags: ['Dense', '可识别图像'],
    license: "MIT",
    commercial: '可商用',
    context: "200K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'hy3-preview',
    title: "Hy3-preview",
    org: "腾讯混元",
    family: "Hunyuan",
    repo: 'tencent/Hy3-preview',
    released: '2026-04-13',
    verified: true,
    summary: "混元第三代开源基座的预览版，为 Hy3 正式版做能力探路。",
    tags: ['MoE', '纯文本'],
    license: "other",
    commercial: '可商用',
    context: "256K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'ling-mini-2-0',
    title: "Ling-mini-2.0",
    org: "蚂蚁集团 inclusionAI",
    family: "Ling",
    repo: 'inclusionAI/Ling-mini-2.0',
    released: '2025-09-08',
    verified: true,
    summary: "百灵的 16B 激活 1.4B 迷你 MoE，端侧高并发场景的开源选择。",
    tags: ['MoE', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'youtu-vl-4b-instruct',
    title: "Youtu-VL-4B",
    org: "腾讯混元",
    family: "Hunyuan",
    repo: 'tencent/Youtu-VL-4B-Instruct',
    released: '2026-01-23',
    verified: true,
    summary: "腾讯优图的 4B 视觉语言模型，端侧做图像问答与 OCR。",
    tags: ['Dense', '可识别图像'],
    license: "other",
    commercial: '可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['llama-cpp', 'ollama'],
  },
  {
    slug: 'ring-mini-2-0',
    title: "Ring-mini-2.0",
    org: "蚂蚁集团 inclusionAI",
    family: "Ling",
    repo: 'inclusionAI/Ring-mini-2.0',
    released: '2025-09-08',
    verified: true,
    summary: "Ring-mini 的 2.0 版本，小激活量下做推理链。",
    tags: ['MoE', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'ling-2-5-1t',
    title: "Ling-2.5-1T",
    org: "蚂蚁集团 inclusionAI",
    family: "Ling",
    repo: 'inclusionAI/Ling-2.5-1T',
    released: '2026-02-14',
    verified: true,
    summary: "百灵 2.5 代的万亿参数基座，激活 50B 级别，MIT 许可。",
    tags: ['MoE', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'ring-2-5-1t',
    title: "Ring-2.5-1T",
    org: "蚂蚁集团 inclusionAI",
    family: "Ling",
    repo: 'inclusionAI/Ring-2.5-1T',
    released: '2026-02-10',
    verified: true,
    summary: "Ring 2.5 代的万亿推理模型，长思维链强化学习路线。",
    tags: ['MoE', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'ling-2-6-1t',
    title: "Ling-2.6-1T",
    org: "蚂蚁集团 inclusionAI",
    family: "Ling",
    repo: 'inclusionAI/Ling-2.6-1T',
    released: '2026-04-29',
    verified: true,
    summary: "百灵 2.6 代的万亿基座，训练数据与配方继续公开。",
    tags: ['MoE', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'ring-2-6-1t',
    title: "Ring-2.6-1T",
    org: "蚂蚁集团 inclusionAI",
    family: "Ling",
    repo: 'inclusionAI/Ring-2.6-1T',
    released: '2026-05-14',
    verified: true,
    summary: "Ring 2.6 代的万亿推理模型，本轮推理能力最强的开源尺寸之一。",
    tags: ['MoE', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'ling-2-6-flash',
    title: "Ling-2.6-flash",
    org: "蚂蚁集团 inclusionAI",
    family: "Ling",
    repo: 'inclusionAI/Ling-2.6-flash',
    released: '2026-04-28',
    verified: true,
    summary: "Ling 2.6 的快速版，低延迟面向在线 agent。",
    tags: ['MoE', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'ling-3-0-tiny',
    title: "Ling-3.0-tiny",
    org: "蚂蚁集团 inclusionAI",
    family: "Ling",
    repo: 'inclusionAI/Ling-3.0-tiny',
    released: '2026-08-10',
    verified: true,
    summary: "百灵第三代的迷你版，把 MoE 压到端侧可跑的量级。",
    tags: ['MoE', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['llama-cpp', 'ollama'],
  },
  {
    slug: 'ling-3-0-flash-vl',
    title: "Ling-3.0-flash-VL",
    org: "蚂蚁集团 inclusionAI",
    family: "Ling",
    repo: 'inclusionAI/Ling-3.0-flash-VL',
    released: '2026-09-04',
    verified: true,
    summary: "Ling 3.0 的视觉版本，在快速档上补上图像输入。",
    tags: ['Dense', '可识别图像'],
    license: "MIT",
    commercial: '可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['vllm'],
  },
  {
    slug: 'llada2-0-mini',
    title: "LLaDA2.0-mini",
    org: "蚂蚁集团 inclusionAI",
    family: "Ling",
    repo: 'inclusionAI/LLaDA2.0-mini',
    released: '2025-11-25',
    verified: true,
    summary: "扩散式语言模型 LLaDA 2.0 的迷你版，16B 激活 1B，非自回归生成路线。",
    tags: ['MoE', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "32K",
    modalities: ['text'],
    deploys: ['vllm'],
  },
  {
    slug: 'internlm3-8b-instruct',
    title: "InternLM3-8B",
    org: "上海 AI Lab",
    family: "InternLM",
    repo: 'internlm/internlm3-8b-instruct',
    released: '2025-01-13',
    verified: true,
    summary: "InternLM3 的 8B 指令版，上海 AI Lab 通用对话模型的开源主力。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'intern-s1-pro',
    title: "Intern-S1-Pro",
    org: "上海 AI Lab",
    family: "InternLM",
    repo: 'internlm/Intern-S1-Pro',
    released: '2026-02-02',
    verified: true,
    summary: "Intern-S1 的科学推理加强版，面向专业学科的长链推理。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'intern-s2-preview',
    title: "Intern-S2-Preview",
    org: "上海 AI Lab",
    family: "InternLM",
    repo: 'internlm/Intern-S2-Preview',
    released: '2026-05-15',
    verified: true,
    summary: "Intern-S2 科学模型的预览版，先放出 36B 档权重供试跑，正式版同期有 397B。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'step3-vl-10b',
    title: "Step3-VL-10B",
    org: "阶跃星辰 StepFun",
    family: "Step",
    repo: 'stepfun-ai/Step3-VL-10B',
    released: '2026-01-13',
    verified: true,
    summary: "Step 3 的 10B 视觉版本，小尺寸做图文理解与推理。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "64K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'atria-dawn-preview',
    title: "Atria-Dawn-Preview",
    org: "上海 AI Lab",
    family: "InternLM",
    repo: 'internlm/Atria-Dawn-Preview',
    released: '2026-09-11',
    verified: true,
    summary: "上海 AI Lab 的 Atria 系列预览版，面向代码与工具使用的通用模型。",
    tags: ['MoE', '纯文本'],
    license: "MIT",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'ernie-4-5-21b-a3b-thinking',
    title: "ERNIE-4.5-21B-A3B-Thinking",
    org: "百度",
    family: "ERNIE",
    repo: 'baidu/ERNIE-4.5-21B-A3B-Thinking',
    released: '2025-09-08',
    verified: true,
    summary: "ERNIE 4.5 的 21B 思考版，激活 3B 做推理链。",
    tags: ['MoE', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'ernie-4-5-vl-28b-a3b-thinking',
    title: "ERNIE-4.5-VL-28B-A3B-Thinking",
    org: "百度",
    family: "ERNIE",
    repo: 'baidu/ERNIE-4.5-VL-28B-A3B-Thinking',
    released: '2025-11-07',
    verified: true,
    summary: "同 28B-A3B 的视觉思考版，把推理链接进多模态输入。",
    tags: ['MoE', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'ernie-4-5-vl-28b-a3b-pt',
    title: "ERNIE-4.5-VL-28B-A3B-PT",
    org: "百度",
    family: "ERNIE",
    repo: 'baidu/ERNIE-4.5-VL-28B-A3B-PT',
    released: '2025-06-28',
    verified: true,
    summary: "ERNIE 4.5 的中量级视觉模型，28B 激活 3B 做多模态理解。",
    tags: ['MoE', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'bagel-7b-mot',
    title: "BAGEL-7B-MoT",
    org: "字节跳动 Seed",
    family: "Seed",
    repo: 'ByteDance-Seed/BAGEL-7B-MoT',
    released: '2025-05-19',
    verified: true,
    summary: "字节的统一多模态模型，7B 同时做图像理解与图像生成。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "32K",
    modalities: ['text', 'image'],
    deploys: ['vllm'],
  },
  {
    slug: 'grok-2',
    title: "Grok 2",
    org: "xAI",
    family: "Grok",
    repo: 'xai-org/grok-2',
    released: '2025-08-22',
    verified: true,
    summary: "xAI 首次放出的开放权重模型，Grok-2 的 269B MoE 权重公开下载。",
    tags: ['MoE', '纯文本'],
    license: "xAI Grok 2 Open Weights License",
    commercial: '有条件可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'eurollm-22b-instruct-2512',
    title: "EuroLLM-22B-Instruct-2512",
    org: "Unbabel / 欧盟项目",
    family: "EuroLLM",
    repo: 'utter-project/EuroLLM-22B-Instruct-2512',
    released: '2025-12-05',
    verified: true,
    summary: "欧盟资助的 EuroLLM 22B 版本，覆盖全部官方语言的开源模型。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "32K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'solar-open2-250b',
    title: "Solar-Open2-250B",
    org: "Upstage",
    family: "Solar",
    repo: 'upstage/Solar-Open2-250B',
    released: '2026-07-22',
    verified: true,
    summary: "韩国自主 AI 项目的第二代成果，250B MoE 从零训练。",
    tags: ['MoE', '纯文本'],
    license: "other",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'apertus-v1-5-8b',
    title: "Apertus-v1.5-8B",
    org: "Swiss AI Initiative",
    family: "Apertus",
    repo: 'swiss-ai/Apertus-v1.5-8B',
    released: '2026-07-24',
    verified: true,
    summary: "Apertus 1.5 代的 8B 版本，把多模态输入加进瑞士国家级开源模型。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "64K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'k-exaone-2-0-750b-a37b',
    title: "K-EXAONE-2.0-750B-A37B",
    org: "LG AI Research",
    family: "EXAONE",
    repo: 'LGAI-EXAONE/K-EXAONE-2.0-750B-A37B',
    released: '2026-07-29',
    verified: true,
    summary: "LG 与韩国政府合作的第二代旗舰，750B 激活 37B，韩语能力最强档。",
    tags: ['MoE', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'apertus-v1-5-70b',
    title: "Apertus-v1.5-70B",
    org: "Swiss AI Initiative",
    family: "Apertus",
    repo: 'swiss-ai/Apertus-v1.5-70B',
    released: '2026-07-24',
    verified: true,
    summary: "Apertus 1.5 的 70B 版本，权重与训练配方继续全公开。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "64K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'exaone-4-5-33b',
    title: "EXAONE-4.5-33B",
    org: "LG AI Research",
    family: "EXAONE",
    repo: 'LGAI-EXAONE/EXAONE-4.5-33B',
    released: '2026-04-04',
    verified: true,
    summary: "EXAONE 4.5 的 33B 多模态版本，LG 首个公开的视觉语言模型。",
    tags: ['Dense', '可识别图像'],
    license: "other",
    commercial: '可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'apertus-8b-instruct-2509',
    title: "Apertus-8B-Instruct-2509",
    org: "Swiss AI Initiative",
    family: "Apertus",
    repo: 'swiss-ai/Apertus-8B-Instruct-2509',
    released: '2025-08-13',
    verified: true,
    summary: "Apertus 的 8B 指令版，端侧可跑的多语言开源模型。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "64K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp', 'ollama'],
  },
  {
    slug: 'exaone-deep-32b',
    title: "EXAONE-Deep-32B",
    org: "LG AI Research",
    family: "EXAONE",
    repo: 'LGAI-EXAONE/EXAONE-Deep-32B',
    released: '2025-03-12',
    verified: true,
    summary: "EXAONE Deep 的 32B 推理模型，数学与代码在同尺寸领先，仅限研究用途。",
    tags: ['Dense', '纯文本'],
    license: "other",
    commercial: '可商用',
    context: "32K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'aya-vision-32b',
    title: "Aya Vision 32B",
    org: "Cohere Labs",
    family: "Aya",
    repo: 'CohereLabs/aya-vision-32b',
    released: '2025-03-02',
    verified: true,
    summary: "Aya Vision 的 32B 版本，覆盖 23 种语言的多模态开源模型。",
    tags: ['Dense', '可识别图像'],
    license: "CC-BY-NC-4.0",
    commercial: '不可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'aya-vision-8b',
    title: "Aya Vision 8B",
    org: "Cohere Labs",
    family: "Aya",
    repo: 'CohereLabs/aya-vision-8b',
    released: '2025-03-02',
    verified: true,
    summary: "Aya Vision 的 8B 版本，端侧做多语言图文理解。",
    tags: ['Dense', '可识别图像'],
    license: "CC-BY-NC-4.0",
    commercial: '不可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'c4ai-command-a-03-2025',
    title: "Command A（03-2025）",
    org: "Cohere",
    family: "Command",
    repo: 'CohereLabs/c4ai-command-a-03-2025',
    released: '2025-03-11',
    verified: true,
    summary: "Command A 的 111B 开放权重版，256K 上下文面向企业 agent，非商业许可。",
    tags: ['Dense', '纯文本'],
    license: "CC-BY-NC-4.0",
    commercial: '不可商用',
    context: "256K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'command-a-reasoning-08-2025',
    title: "Command A Reasoning",
    org: "Cohere",
    family: "Command",
    repo: 'CohereLabs/command-a-reasoning-08-2025',
    released: '2025-08-12',
    verified: true,
    summary: "Command A 的推理版本，企业场景下的长思维链与工具调用。",
    tags: ['Dense', '纯文本'],
    license: "CC-BY-NC-4.0",
    commercial: '不可商用',
    context: "256K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'north-micro-vision-instruct',
    title: "North-Micro-Vision-Instruct",
    org: "Cohere",
    family: "Command",
    repo: 'CohereLabs/North-Micro-Vision-Instruct',
    released: '2026-08-10',
    verified: true,
    summary: "North 系列的微型视觉指令模型，端侧做文档与界面理解。",
    tags: ['Dense', '可识别图像'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text', 'image'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'reka-edge-2603',
    title: "Reka Edge",
    org: "Reka AI",
    family: "Reka",
    repo: 'RekaAI/reka-edge-2603',
    released: '2026-03-11',
    verified: true,
    summary: "Reka 面向机器人与边缘设备的视觉模型，2603 批次。",
    tags: ['Dense', '可识别图像'],
    license: "other",
    commercial: '可商用',
    context: "32K",
    modalities: ['text', 'image'],
    deploys: ['vllm'],
  },
  {
    slug: 'reka-flash-3',
    title: "Reka Flash 3",
    org: "Reka AI",
    family: "Reka",
    repo: 'RekaAI/reka-flash-3',
    released: '2025-03-11',
    verified: true,
    summary: "Reka 从零训练的 21B 通用推理模型，小尺寸里对标 o1-mini 的一档。",
    tags: ['Dense', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'sglang'],
  },
  {
    slug: 'diffucoder-7b-cpgrpo',
    title: "DiffuCoder-7B-cpGRPO",
    org: "Apple",
    family: "DiffuCoder",
    repo: 'apple/DiffuCoder-7B-cpGRPO',
    released: '2025-07-01',
    verified: true,
    summary: "扩散式代码生成模型，7B 用非自回归解码做代码补全。",
    tags: ['Dense', '纯文本'],
    license: "apple-amlr",
    commercial: '可商用',
    context: "32K",
    modalities: ['text'],
    deploys: ['vllm'],
  },
  {
    slug: 'fastvlm-7b',
    title: "FastVLM-7B",
    org: "Apple",
    family: "FastVLM",
    repo: 'apple/FastVLM-7B',
    released: '2025-08-25',
    verified: true,
    summary: "Apple 的快速视觉语言模型，7B 以低延迟做端侧图像理解。",
    tags: ['Dense', '可识别图像'],
    license: "apple-amlr",
    commercial: '可商用',
    context: "32K",
    modalities: ['text', 'image'],
    deploys: ['vllm'],
  },
  {
    slug: 'zaya1-8b',
    title: "ZAYA1-8B",
    org: "Zyphra",
    family: "ZAYA",
    repo: 'Zyphra/ZAYA1-8B',
    released: '2026-05-04',
    verified: true,
    summary: "全流程在 AMD GPU 上训练的 8B MoE（激活 0.6B），证明非 NVIDIA 路线可行。",
    tags: ['MoE', '纯文本'],
    license: "Apache-2.0",
    commercial: '可商用',
    context: "128K",
    modalities: ['text'],
    deploys: ['vllm', 'llama-cpp'],
  },
  {
    slug: 'lensvlm-9b',
    title: "LensVLM-9B",
    org: "Apple",
    family: "LensVLM",
    repo: 'apple/LensVLM-9B',
    released: '2026-09-21',
    verified: true,
    summary: "Apple 的镜头式视觉模型，9B 面向端侧细粒度图像问答。",
    tags: ['Dense', '可识别图像'],
    license: "apple-amlr",
    commercial: '可商用',
    context: "32K",
    modalities: ['text', 'image'],
    deploys: ['vllm'],
  },
];
